# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_gcmessages_client_tournament.proto
# plugin: python-betterproto

from dataclasses import dataclass
from typing import List

import betterproto

from .dota_client_enums import ETournamentGameState, ETournamentNodeState, ETournamentState, ETournamentTemplate


class ETournamentEvent(betterproto.Enum):
    NONE = 0
    TournamentCreated = 1
    TournamentsMerged = 2
    GameOutcome = 3
    TeamGivenBye = 4
    TournamentCanceledByAdmin = 5
    TeamAbandoned = 6
    ScheduledGameStarted = 7
    Canceled = 8
    TeamParticipationTimedOutEntryFeeRefund = 9
    TeamParticipationTimedOutEntryFeeForfeit = 10
    TeamParticipationTimedOutGrantedVictory = 11


@dataclass
class CMsgDOTATournamentInfo(betterproto.Message):
    league_id: int = betterproto.uint32_field(1)
    phase_list: List["CMsgDOTATournamentInfoPhase"] = betterproto.message_field(2)
    teams_list: List["CMsgDOTATournamentInfoTeam"] = betterproto.message_field(3)
    upcoming_matches_list: List["CMsgDOTATournamentInfoUpcomingMatch"] = betterproto.message_field(4)
    news_list: List["CMsgDOTATournamentInfoNews"] = betterproto.message_field(5)


@dataclass
class CMsgDOTATournamentInfoPhaseGroup(betterproto.Message):
    group_id: int = betterproto.uint32_field(1)
    group_name: str = betterproto.string_field(2)


@dataclass
class CMsgDOTATournamentInfoPhase(betterproto.Message):
    phase_id: int = betterproto.uint32_field(1)
    phase_name: str = betterproto.string_field(2)
    type_id: int = betterproto.uint32_field(3)
    iterations: int = betterproto.uint32_field(4)
    min_start_time: int = betterproto.uint32_field(5)
    max_start_time: int = betterproto.uint32_field(6)
    group_list: List["CMsgDOTATournamentInfoPhaseGroup"] = betterproto.message_field(7)


@dataclass
class CMsgDOTATournamentInfoTeam(betterproto.Message):
    team_id: int = betterproto.uint32_field(1)
    name: str = betterproto.string_field(2)
    tag: str = betterproto.string_field(3)
    team_logo: int = betterproto.uint64_field(4)
    eliminated: bool = betterproto.bool_field(5)


@dataclass
class CMsgDOTATournamentInfoUpcomingMatch(betterproto.Message):
    series_id: int = betterproto.uint32_field(1)
    team1_id: int = betterproto.uint32_field(2)
    team2_id: int = betterproto.uint32_field(3)
    bo: int = betterproto.uint32_field(4)
    stage_name: str = betterproto.string_field(5)
    start_time: int = betterproto.uint32_field(6)
    winner_stage: str = betterproto.string_field(7)
    loser_stage: str = betterproto.string_field(8)
    team1_tag: str = betterproto.string_field(9)
    team2_tag: str = betterproto.string_field(10)
    team1_prev_opponent_tag: str = betterproto.string_field(11)
    team2_prev_opponent_tag: str = betterproto.string_field(12)
    team1_logo: int = betterproto.uint64_field(13)
    team2_logo: int = betterproto.uint64_field(14)
    team1_prev_opponent_logo: int = betterproto.uint64_field(15)
    team2_prev_opponent_logo: int = betterproto.uint64_field(16)
    team1_prev_opponent_id: int = betterproto.uint32_field(17)
    team2_prev_opponent_id: int = betterproto.uint32_field(18)
    team1_prev_match_score: int = betterproto.uint32_field(19)
    team1_prev_match_opponent_score: int = betterproto.uint32_field(20)
    team2_prev_match_score: int = betterproto.uint32_field(21)
    team2_prev_match_opponent_score: int = betterproto.uint32_field(22)
    phase_type: int = betterproto.uint32_field(23)
    team1_score: int = betterproto.uint32_field(24)
    team2_score: int = betterproto.uint32_field(25)
    phase_id: int = betterproto.uint32_field(26)


@dataclass
class CMsgDOTATournamentInfoNews(betterproto.Message):
    link: str = betterproto.string_field(1)
    title: str = betterproto.string_field(2)
    image: str = betterproto.string_field(3)
    timestamp: int = betterproto.uint32_field(4)


@dataclass
class CMsgRequestWeekendTourneySchedule(betterproto.Message):
    pass


@dataclass
class CMsgWeekendTourneySchedule(betterproto.Message):
    divisions: List["CMsgWeekendTourneyScheduleDivision"] = betterproto.message_field(1)


@dataclass
class CMsgWeekendTourneyScheduleDivision(betterproto.Message):
    division_code: int = betterproto.uint32_field(1)
    time_window_open: int = betterproto.uint32_field(2)
    time_window_close: int = betterproto.uint32_field(3)
    time_window_open_next: int = betterproto.uint32_field(4)
    trophy_id: int = betterproto.uint32_field(5)
    free_weekend: bool = betterproto.bool_field(6)


@dataclass
class CMsgWeekendTourneyOpts(betterproto.Message):
    participating: bool = betterproto.bool_field(1)
    division_id: int = betterproto.uint32_field(2)
    buyin: int = betterproto.uint32_field(3)
    skill_level: int = betterproto.uint32_field(4)
    match_groups: int = betterproto.uint32_field(5)
    team_id: int = betterproto.uint32_field(6)
    pickup_team_name: str = betterproto.string_field(7)
    pickup_team_logo: int = betterproto.uint64_field(8)


@dataclass
class CMsgWeekendTourneyLeave(betterproto.Message):
    pass


@dataclass
class CMsgDOTATournament(betterproto.Message):
    tournament_id: int = betterproto.uint32_field(1)
    division_id: int = betterproto.uint32_field(2)
    schedule_time: int = betterproto.uint32_field(3)
    skill_level: int = betterproto.uint32_field(4)
    tournament_template: "ETournamentTemplate" = betterproto.enum_field(5)
    state: "ETournamentState" = betterproto.enum_field(6)
    state_seq_num: int = betterproto.uint32_field(10)
    season_trophy_id: int = betterproto.uint32_field(11)
    teams: List["CMsgDOTATournamentTeam"] = betterproto.message_field(7)
    games: List["CMsgDOTATournamentGame"] = betterproto.message_field(8)
    nodes: List["CMsgDOTATournamentNode"] = betterproto.message_field(9)


@dataclass
class CMsgDOTATournamentTeam(betterproto.Message):
    team_gid: float = betterproto.fixed64_field(1)
    node_or_state: int = betterproto.uint32_field(2)
    players: List[int] = betterproto.uint32_field(3)
    player_buyin: List[int] = betterproto.uint32_field(9)
    player_skill_level: List[int] = betterproto.uint32_field(10)
    match_group_mask: int = betterproto.uint32_field(12)
    team_id: int = betterproto.uint32_field(4)
    team_name: str = betterproto.string_field(5)
    team_base_logo: int = betterproto.uint64_field(7)
    team_ui_logo: int = betterproto.uint64_field(8)


@dataclass
class CMsgDOTATournamentGame(betterproto.Message):
    node_idx: int = betterproto.uint32_field(1)
    lobby_id: float = betterproto.fixed64_field(2)
    match_id: int = betterproto.uint64_field(3)
    team_a_good: bool = betterproto.bool_field(4)
    state: "ETournamentGameState" = betterproto.enum_field(5)
    start_time: int = betterproto.uint32_field(6)


@dataclass
class CMsgDOTATournamentNode(betterproto.Message):
    node_id: int = betterproto.uint32_field(1)
    team_idx_a: int = betterproto.uint32_field(2)
    team_idx_b: int = betterproto.uint32_field(3)
    node_state: "ETournamentNodeState" = betterproto.enum_field(4)


@dataclass
class CMsgDOTATournamentStateChange(betterproto.Message):
    new_tournament_id: int = betterproto.uint32_field(1)
    event: "ETournamentEvent" = betterproto.enum_field(2)
    new_tournament_state: "ETournamentState" = betterproto.enum_field(3)
    game_changes: List["CMsgDOTATournamentStateChangeGameChange"] = betterproto.message_field(4)
    team_changes: List["CMsgDOTATournamentStateChangeTeamChange"] = betterproto.message_field(5)
    merged_tournament_ids: List[int] = betterproto.uint32_field(6)
    state_seq_num: int = betterproto.uint32_field(7)


@dataclass
class CMsgDOTATournamentStateChangeGameChange(betterproto.Message):
    match_id: int = betterproto.uint64_field(1)
    new_state: "ETournamentGameState" = betterproto.enum_field(2)


@dataclass
class CMsgDOTATournamentStateChangeTeamChange(betterproto.Message):
    team_gid: int = betterproto.uint64_field(1)
    new_node_or_state: int = betterproto.uint32_field(2)
    old_node_or_state: int = betterproto.uint32_field(3)


@dataclass
class CMsgDOTATournamentRequest(betterproto.Message):
    tournament_id: int = betterproto.uint32_field(1)
    client_tournament_gid: int = betterproto.uint64_field(2)


@dataclass
class CMsgDOTATournamentResponse(betterproto.Message):
    result: int = betterproto.uint32_field(1)
    tournament: "CMsgDOTATournament" = betterproto.message_field(2)


@dataclass
class CMsgDOTAClearTournamentGame(betterproto.Message):
    tournament_id: int = betterproto.uint32_field(1)
    game_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgDOTAWeekendTourneyPlayerSkillLevelStats(betterproto.Message):
    skill_level: int = betterproto.uint32_field(1)
    times_won_0: int = betterproto.uint32_field(2)
    times_won_1: int = betterproto.uint32_field(3)
    times_won_2: int = betterproto.uint32_field(4)
    times_won_3: int = betterproto.uint32_field(5)
    times_bye_and_lost: int = betterproto.uint32_field(6)
    times_bye_and_won: int = betterproto.uint32_field(7)
    times_unusual_champ: int = betterproto.uint32_field(10)
    total_games_won: int = betterproto.uint32_field(8)
    score: int = betterproto.uint32_field(9)


@dataclass
class CMsgDOTAWeekendTourneyPlayerStats(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    season_trophy_id: int = betterproto.uint32_field(2)
    skill_levels: List["CMsgDOTAWeekendTourneyPlayerSkillLevelStats"] = betterproto.message_field(3)
    current_tier: int = betterproto.uint32_field(4)


@dataclass
class CMsgDOTAWeekendTourneyPlayerStatsRequest(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    season_trophy_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgDOTAWeekendTourneyPlayerHistoryRequest(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    season_trophy_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgDOTAWeekendTourneyPlayerHistory(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    tournaments: List["CMsgDOTAWeekendTourneyPlayerHistoryTournament"] = betterproto.message_field(3)


@dataclass
class CMsgDOTAWeekendTourneyPlayerHistoryTournament(betterproto.Message):
    tournament_id: int = betterproto.uint32_field(1)
    start_time: int = betterproto.uint32_field(2)
    tournament_tier: int = betterproto.uint32_field(3)
    team_id: int = betterproto.uint32_field(4)
    team_date: int = betterproto.uint32_field(5)
    team_result: int = betterproto.uint32_field(6)
    account_id: List[int] = betterproto.uint32_field(7)
    team_name: str = betterproto.string_field(8)
    season_trophy_id: int = betterproto.uint32_field(9)


@dataclass
class CMsgDOTAWeekendTourneyParticipationDetails(betterproto.Message):
    divisions: List["CMsgDOTAWeekendTourneyParticipationDetailsDivision"] = betterproto.message_field(1)


@dataclass
class CMsgDOTAWeekendTourneyParticipationDetailsTier(betterproto.Message):
    tier: int = betterproto.uint32_field(1)
    players: int = betterproto.uint32_field(2)
    teams: int = betterproto.uint32_field(3)
    winning_teams: int = betterproto.uint32_field(4)
    players_streak_2: int = betterproto.uint32_field(5)
    players_streak_3: int = betterproto.uint32_field(6)
    players_streak_4: int = betterproto.uint32_field(7)
    players_streak_5: int = betterproto.uint32_field(8)


@dataclass
class CMsgDOTAWeekendTourneyParticipationDetailsDivision(betterproto.Message):
    division_id: int = betterproto.uint32_field(1)
    schedule_time: int = betterproto.uint32_field(2)
    tiers: List["CMsgDOTAWeekendTourneyParticipationDetailsTier"] = betterproto.message_field(3)
