# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_gcmessages_client_chat.proto
# plugin: python-betterproto

from dataclasses import dataclass
from typing import List

import betterproto

from .dota_shared_enums import DotaChatChannelType


class CMsgGcToClientPrivateChatResponseResult(betterproto.Enum):
    Success = 0
    FailureCreationLock = 1
    FailureSqlTransaction = 2
    FailureSdoLoad = 3
    FailureNoPermission = 4
    FailureAlreadyMember = 5
    FailureNotAMember = 7
    FailureNoRemainingAdmins = 8
    FailureNoRoom = 9
    FailureCreationRateLimited = 10
    FailureUnknownChannelName = 11
    FailureUnknownUser = 12
    FailureUnknownError = 13
    FailureCannotKickAdmin = 14
    FailureAlreadyAdmin = 15


class CMsgDotaJoinChatChannelResponseResult(betterproto.Enum):
    JoinSuccess = 0
    InvalidChannelType = 1
    AccountNotFound = 2
    AchFailed = 3
    UserInTooManyChannels = 4
    RateLimitExceeded = 5
    ChannelFull = 6
    ChannelFullOverflowed = 7
    FailedToAddUser = 8
    ChannelTypeDisabled = 9
    PrivateChatCreateFailed = 10
    PrivateChatNoPermission = 11
    PrivateChatCreateLockFailed = 12
    PrivateChatKicked = 13
    UserNotAllowed = 14


@dataclass(eq=False, repr=False)
class CMsgClientToGcPrivateChatInvite(betterproto.Message):
    private_chat_channel_name: str = betterproto.string_field(1)
    invited_account_id: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcPrivateChatKick(betterproto.Message):
    private_chat_channel_name: str = betterproto.string_field(1)
    kick_account_id: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcPrivateChatPromote(betterproto.Message):
    private_chat_channel_name: str = betterproto.string_field(1)
    promote_account_id: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcPrivateChatDemote(betterproto.Message):
    private_chat_channel_name: str = betterproto.string_field(1)
    demote_account_id: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcToClientPrivateChatResponse(betterproto.Message):
    private_chat_channel_name: str = betterproto.string_field(1)
    result: "CMsgGcToClientPrivateChatResponseResult" = betterproto.enum_field(2)
    username: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class CMsgClientToGcPrivateChatInfoRequest(betterproto.Message):
    private_chat_channel_name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcToClientPrivateChatInfoResponse(betterproto.Message):
    private_chat_channel_name: str = betterproto.string_field(1)
    members: List["CMsgGcToClientPrivateChatInfoResponseMember"] = betterproto.message_field(2)
    creator: int = betterproto.uint32_field(3)
    creation_date: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CMsgGcToClientPrivateChatInfoResponseMember(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    name: str = betterproto.string_field(2)
    status: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CMsgDotaJoinChatChannel(betterproto.Message):
    channel_name: str = betterproto.string_field(2)
    channel_type: "DotaChatChannelType" = betterproto.enum_field(4)


@dataclass(eq=False, repr=False)
class CMsgDotaLeaveChatChannel(betterproto.Message):
    channel_id: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcChatReportPublicSpam(betterproto.Message):
    channel_id: int = betterproto.uint64_field(1)
    channel_user_id: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgDotaClientIgnoredUser(betterproto.Message):
    ignored_account_id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class CMsgDotaChatMessage(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    channel_id: int = betterproto.uint64_field(2)
    persona_name: str = betterproto.string_field(3)
    text: str = betterproto.string_field(4)
    timestamp: int = betterproto.uint32_field(5)
    suggest_invite_account_id: int = betterproto.uint32_field(6)
    suggest_invite_name: str = betterproto.string_field(7)
    fantasy_draft_owner_account_id: int = betterproto.uint32_field(8)
    fantasy_draft_player_account_id: int = betterproto.uint32_field(9)
    event_id: int = betterproto.uint32_field(10)
    suggest_invite_to_lobby: bool = betterproto.bool_field(11)
    event_points: int = betterproto.uint32_field(12)
    coin_flip: bool = betterproto.bool_field(13)
    player_id: int = betterproto.int32_field(14)
    share_profile_account_id: int = betterproto.uint32_field(15)
    channel_user_id: int = betterproto.uint32_field(16)
    dice_roll: "CMsgDotaChatMessageDiceRoll" = betterproto.message_field(17)
    share_party_id: int = betterproto.uint64_field(18)
    share_lobby_id: int = betterproto.uint64_field(19)
    share_lobby_custom_game_id: int = betterproto.uint64_field(20)
    share_lobby_passkey: str = betterproto.string_field(21)
    private_chat_channel_id: int = betterproto.uint32_field(22)
    status: int = betterproto.uint32_field(23)
    legacy_battle_cup_victory: bool = betterproto.bool_field(24)
    battle_cup_streak: int = betterproto.uint32_field(29)
    badge_level: int = betterproto.uint32_field(25)
    suggest_pick_hero_id: int = betterproto.uint32_field(26)
    suggest_pick_hero_role: str = betterproto.string_field(27)
    suggest_ban_hero_id: int = betterproto.uint32_field(30)
    trivia_answer: "CMsgDotaChatMessageTriviaAnswered" = betterproto.message_field(32)
    requested_ability_id: int = betterproto.uint32_field(33)
    chat_flags: int = betterproto.uint32_field(34)
    started_finding_match: bool = betterproto.bool_field(35)
    ctrl_is_down: bool = betterproto.bool_field(36)


@dataclass(eq=False, repr=False)
class CMsgDotaChatMessageDiceRoll(betterproto.Message):
    roll_min: int = betterproto.int32_field(1)
    roll_max: int = betterproto.int32_field(2)
    result: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class CMsgDotaChatMessageTriviaAnswered(betterproto.Message):
    question_id: int = betterproto.uint32_field(1)
    answer_index: int = betterproto.uint32_field(2)
    party_questions_correct: int = betterproto.uint32_field(3)
    party_questions_viewed: int = betterproto.uint32_field(4)
    party_trivia_points: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class CMsgDotaChatMember(betterproto.Message):
    steam_id: int = betterproto.fixed64_field(1)
    persona_name: str = betterproto.string_field(2)
    channel_user_id: int = betterproto.uint32_field(3)
    status: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CMsgDotaJoinChatChannelResponse(betterproto.Message):
    response: int = betterproto.uint32_field(1)
    channel_name: str = betterproto.string_field(2)
    channel_id: int = betterproto.fixed64_field(3)
    max_members: int = betterproto.uint32_field(4)
    members: List["CMsgDotaChatMember"] = betterproto.message_field(5)
    channel_type: "DotaChatChannelType" = betterproto.enum_field(6)
    result: "CMsgDotaJoinChatChannelResponseResult" = betterproto.enum_field(7)
    gc_initiated_join: bool = betterproto.bool_field(8)
    channel_user_id: int = betterproto.uint32_field(9)
    welcome_message: str = betterproto.string_field(10)


@dataclass(eq=False, repr=False)
class CMsgDotaChatChannelFullUpdate(betterproto.Message):
    channel_id: int = betterproto.fixed64_field(1)
    members: List["CMsgDotaChatMember"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CMsgDotaOtherJoinedChatChannel(betterproto.Message):
    channel_id: int = betterproto.fixed64_field(1)
    persona_name: str = betterproto.string_field(2)
    steam_id: int = betterproto.fixed64_field(3)
    channel_user_id: int = betterproto.uint32_field(4)
    status: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class CMsgDotaOtherLeftChatChannel(betterproto.Message):
    channel_id: int = betterproto.fixed64_field(1)
    steam_id: int = betterproto.fixed64_field(2)
    channel_user_id: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CMsgDotaChatChannelMemberUpdate(betterproto.Message):
    channel_id: int = betterproto.fixed64_field(1)
    left_steam_ids: List[int] = betterproto.fixed64_field(2)
    joined_members: List["CMsgDotaChatChannelMemberUpdateJoinedMember"] = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class CMsgDotaChatChannelMemberUpdateJoinedMember(betterproto.Message):
    steam_id: int = betterproto.fixed64_field(1)
    persona_name: str = betterproto.string_field(2)
    channel_user_id: int = betterproto.uint32_field(3)
    status: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CMsgDotaRequestChatChannelList(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class CMsgDotaRequestChatChannelListResponse(betterproto.Message):
    channels: List["CMsgDotaRequestChatChannelListResponseChatChannel"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CMsgDotaRequestChatChannelListResponseChatChannel(betterproto.Message):
    channel_name: str = betterproto.string_field(1)
    num_members: int = betterproto.uint32_field(2)
    channel_type: "DotaChatChannelType" = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class CMsgDotaChatGetUserList(betterproto.Message):
    channel_id: int = betterproto.fixed64_field(1)


@dataclass(eq=False, repr=False)
class CMsgDotaChatGetUserListResponse(betterproto.Message):
    channel_id: int = betterproto.fixed64_field(1)
    members: List["CMsgDotaChatGetUserListResponseMember"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CMsgDotaChatGetUserListResponseMember(betterproto.Message):
    steam_id: int = betterproto.fixed64_field(1)
    persona_name: str = betterproto.string_field(2)
    channel_user_id: int = betterproto.uint32_field(3)
    status: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CMsgDotaChatGetMemberCount(betterproto.Message):
    channel_name: str = betterproto.string_field(1)
    channel_type: "DotaChatChannelType" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class CMsgDotaChatGetMemberCountResponse(betterproto.Message):
    channel_name: str = betterproto.string_field(1)
    channel_type: "DotaChatChannelType" = betterproto.enum_field(2)
    member_count: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CMsgDotaChatRegionsEnabled(betterproto.Message):
    enable_all_regions: bool = betterproto.bool_field(1)
    enabled_regions: List["CMsgDotaChatRegionsEnabledRegion"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CMsgDotaChatRegionsEnabledRegion(betterproto.Message):
    min_latitude: float = betterproto.float_field(1)
    max_latitude: float = betterproto.float_field(2)
    min_longitude: float = betterproto.float_field(3)
    max_longitude: float = betterproto.float_field(4)
