# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_gcmessages_common_match_management.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class ELaneSelection(betterproto.Enum):
    k_ELaneSelection_SAFELANE = 0
    k_ELaneSelection_OFFLANE = 1
    k_ELaneSelection_MIDLANE = 2
    k_ELaneSelection_SUPPORT_SOFT = 3
    k_ELaneSelection_SUPPORT_HARD = 4


class ELaneSelectionFlags(betterproto.Enum):
    k_ELaneSelectionFlags_None = 0
    k_ELaneSelectionFlags_SAFELANE = 1
    k_ELaneSelectionFlags_OFFLANE = 2
    k_ELaneSelectionFlags_MIDLANE = 4
    k_ELaneSelectionFlags_CORE = 7
    k_ELaneSelectionFlags_SUPPORT_SOFT = 8
    k_ELaneSelectionFlags_SUPPORT_HARD = 16
    k_ELaneSelectionFlags_SUPPORT = 24
    k_ELaneSelectionFlags_ALL = 31


class EPartyMatchmakingFlags(betterproto.Enum):
    k_EPartyMatchmakingFlags_None = 0
    k_EPartyMatchmakingFlags_LargeRankSpread = 1


class EHighPriorityMMState(betterproto.Enum):
    k_EHighPriorityMM_Unknown = 0
    k_EHighPriorityMM_MissingMMData = 1
    k_EHighPriorityMM_ResourceMissing = 2
    k_EHighPriorityMM_ManuallyDisabled = 3
    k_EHighPriorityMM_Min_Enabled = 64
    k_EHighPriorityMM_AllRolesSelected = 65
    k_EHighPriorityMM_UsingResource = 66
    k_EHighPriorityMM_FiveStack = 67
    k_EHighPriorityMM_HighDemand = 68


class LobbyDotaTVDelay(betterproto.Enum):
    LobbyDotaTV_10 = 0
    LobbyDotaTV_120 = 1
    LobbyDotaTV_300 = 2


class LobbyDotaPauseSetting(betterproto.Enum):
    LobbyDotaPauseSetting_Unlimited = 0
    LobbyDotaPauseSetting_Limited = 1
    LobbyDotaPauseSetting_Disabled = 2


class EReadyCheckStatus(betterproto.Enum):
    k_EReadyCheckStatus_Unknown = 0
    k_EReadyCheckStatus_NotReady = 1
    k_EReadyCheckStatus_Ready = 2


class EReadyCheckRequestResult(betterproto.Enum):
    k_EReadyCheckRequestResult_Success = 0
    k_EReadyCheckRequestResult_AlreadyInProgress = 1
    k_EReadyCheckRequestResult_NotInParty = 2
    k_EReadyCheckRequestResult_SendError = 3
    k_EReadyCheckRequestResult_UnknownError = 4


class EMatchBehaviorScoreVariance(betterproto.Enum):
    k_EMatchBehaviorScoreVariance_Invalid = 0
    k_EMatchBehaviorScoreVariance_Low = 1
    k_EMatchBehaviorScoreVariance_Medium = 2
    k_EMatchBehaviorScoreVariance_High = 3


class CSODOTAPartyState(betterproto.Enum):
    UI = 0
    FINDING_MATCH = 1
    IN_MATCH = 2


class CSODOTALobbyState(betterproto.Enum):
    UI = 0
    READYUP = 4
    SERVERSETUP = 1
    RUN = 2
    POSTGAME = 3
    NOTREADY = 5
    SERVERASSIGN = 6


class CSODOTALobbyLobbyType(betterproto.Enum):
    INVALID = -1
    CASUAL_MATCH = 0
    PRACTICE = 1
    COOP_BOT_MATCH = 4
    LEGACY_TEAM_MATCH = 5
    LEGACY_SOLO_QUEUE_MATCH = 6
    COMPETITIVE_MATCH = 7
    CASUAL_1V1_MATCH = 8
    WEEKEND_TOURNEY = 9
    LOCAL_BOT_MATCH = 10
    SPECTATOR = 11
    EVENT_MATCH = 12
    GAUNTLET = 13


class CMvpDataCMvpDataMvpDatumCMvpDataCMvpDataMvpDatumMvpAccoladeMvpAccoladeType(
    betterproto.Enum
):
    kills = 1
    deaths = 2
    assists = 3
    net_worth = 5
    item_value = 6
    support_gold_spent = 7
    wards_placed = 8
    dewards = 9
    camps_stacked = 10
    last_hits = 11
    denies = 12
    kKillEaterEvent_Killing_Sprees = 13
    kKillEaterEvent_Godlike = 14
    kKillEaterEvent_Towers_Destroyed = 15
    kKillEaterEventType_Invoker_SunstrikeKills = 16
    kKillEaterEventType_Axe_Culls = 17
    kKillEaterEventType_Axe_BattleHungerKills = 18
    kKillEaterEventType_LowHealthKills = 19
    kKillEaterEventType_Invoker_TornadoKills = 20
    kKillEaterEventType_Sven_DoubleStuns = 21
    kKillEaterEventType_Sven_WarcryAssists = 22
    kKillEaterEventType_Sven_CleaveDoubleKills = 23
    kKillEaterEventType_Sven_TeleportInterrupts = 24
    kKillEaterEventType_Faceless_MultiChrono = 25
    kKillEaterEventType_Faceless_ChronoKills = 26
    kKillEaterEventType_Ursa_MultiShocks = 27
    kKillEaterEventType_RoshanKills = 28
    kKillEaterEventType_Lion_FingerKills = 29
    kKillEaterEventType_Riki_SmokedHeroKills = 32
    kKillEaterEventType_HeroesRevealedWithDust = 33
    kKillEaterEventType_SkeletonKing_ReincarnationKills = 34
    kKillEaterEventType_Skywrath_FlareKills = 35
    kKillEaterEventType_Leshrac_SplitEarthStuns = 36
    kKillEaterEventType_Mirana_MaxStunArrows = 37
    kKillEaterEventType_PhantomAssassin_CoupdeGraceCrits = 38
    kKillEaterEventType_PhantomAssassin_DaggerCrits = 39
    kKillEaterEventType_Meepo_Earthbinds = 40
    kKillEaterEventType_Bloodseeker_RuptureKills = 41
    kKillEaterEventType_Slark_LeashedEnemies = 42
    kKillEaterEventType_Disruptor_FountainGlimpses = 43
    kKillEaterEventType_Rubick_SpellsStolen = 44
    kKillEaterEventType_Rubick_UltimatesStolen = 45
    kKillEaterEventType_Doom_EnemiesDoomed = 46
    kKillEaterEventType_Omniknight_Purifications = 47
    kKillEaterEventType_Omniknight_AlliesRepelled = 48
    kKillEaterEventType_Omniknight_EnemiesRepelled = 49
    kKillEaterEventType_Warlock_FiveHeroFatalBonds = 50
    kKillEaterEventType_CrystalMaiden_FrostbittenEnemies = 51
    kKillEaterEventType_CrystalMaiden_CrystalNovas = 52
    kKillEaterEventType_Kunkka_DoubleHeroTorrents = 53
    kKillEaterEventType_Kunkka_TripleHeroGhostShips = 54
    kKillEaterEventType_NagaSiren_EnemiesEnsnared = 55
    kKillEaterEventType_NagaSiren_TripleHeroRipTides = 56
    kKillEaterEventType_Lycan_KillsDuringShapeshift = 57
    kKillEaterEventType_Pudge_DismemberKills = 58
    kKillEaterEventType_Pudge_EnemyHeroesHooked = 59
    kKillEaterEventType_Pudge_HookKills = 60
    kKillEaterEventType_Pudge_UnseenEnemyHeroesHooked = 61
    kKillEaterEventType_DrowRanger_EnemiesSilenced = 62
    kKillEaterEventType_DrowRanger_MultiHeroSilences = 63
    kKillEaterEventType_DrowRanger_SilencedKills = 64
    kKillEaterEventType_DrowRanger_FrostArrowKills = 65
    kKillEaterEventType_DragonKnight_KillsInDragonForm = 66
    kKillEaterEventType_DragonKnight_BreatheFireKills = 67
    kKillEaterEventType_DragonKnight_SplashKills = 68
    kKillEaterEventType_WitchDoctor_CaskStuns = 69
    kKillEaterEventType_WitchDoctor_MaledictKills = 70
    kKillEaterEventType_WitchDoctor_MultiHeroMaledicts = 71
    kKillEaterEventType_WitchDoctor_DeathWardKills = 72
    kKillEaterEventType_Disruptor_ThunderStrikeKills = 73
    kKillEaterEventType_Disruptor_HeroesGlimpsed = 74
    kKillEaterEventType_CrystalMaiden_FreezingFieldKills = 75
    kKillEaterEventType_Medusa_EnemiesPetrified = 77
    kKillEaterEventType_Warlock_FatalBondsKills = 78
    kKillEaterEventType_Warlock_GolemKills = 79
    kKillEaterEventType_Tusk_WalrusPunches = 80
    kKillEaterEventType_Tusk_SnowballStuns = 81
    kKillEaterEventType_Earthshaker_FissureStuns = 82
    kKillEaterEventType_Earthshaker_3HeroEchoslams = 83
    kKillEaterEventType_SandKing_BurrowstrikeStuns = 84
    kKillEaterEventType_SandKing_EpicenterKills = 85
    kKillEaterEventType_SkywrathMage_AncientSealKills = 86
    kKillEaterEventType_SkywrathMage_ConcussiveShotKills = 87
    kKillEaterEventType_Luna_LucentBeamKills = 88
    kKillEaterEventType_Luna_EclipseKills = 89
    kKillEaterEventType_KeeperOfTheLight_IlluminateKills = 90
    kKillEaterEventType_KeeperOfTheLight_ManaLeakStuns = 91
    kKillEaterEventType_KeeperOfTheLight_TeammatesRecalled = 92
    kKillEaterEventType_LegionCommander_DuelsWon = 93
    kKillEaterEventType_Beastmaster_RoarKills = 94
    kKillEaterEventType_Beastmaster_RoarMultiKills = 95
    kKillEaterEventType_Windrunner_FocusFireBuildings = 96
    kKillEaterEventType_Windrunner_PowershotKills = 97
    kKillEaterEventType_PhantomAssassin_DaggerLastHits = 98
    kKillEaterEventType_PhantomAssassin_PhantomStrikeKills = 99
    kKillEaterEventType_DeathProphet_CryptSwarmKills = 100
    kKillEaterEventType_DeathProphet_ExorcismBuildingKills = 101
    kKillEaterEventType_DeathProphet_ExorcismSpiritsSummoned = 102
    kKillEaterEventType_DeathProphet_MultiHeroSilences = 103
    kKillEaterEventType_Abaddon_MistCoilKills = 104
    kKillEaterEventType_Abaddon_MistCoilHealed = 105
    kKillEaterEventType_Abaddon_AphoticShieldKills = 106
    kKillEaterEventType_Lich_ChainFrostTripleKills = 107
    kKillEaterEventType_Lich_ChainFrostMultiKills = 108
    kKillEaterEventType_Lich_ChainFrostBounces = 109
    kKillEaterEventType_Ursa_EnragedKills = 110
    kKillEaterEventType_Ursa_EarthshockKills = 111
    kKillEaterEventType_Lina_LagunaBladeKills = 112
    kKillEaterEventType_Lina_DragonSlaveKills = 113
    kKillEaterEventType_Lina_LightStrikeArrayStuns = 114
    kKillEaterEvent_Barracks_Destroyed = 115
    kKillEaterEvent_TemplarAssassin_MeldKills = 116
    kKillEaterEvent_TemplarAssassin_HeroesSlowed = 117
    kKillEaterEvent_Sniper_AssassinationKills = 118
    kKillEaterEvent_Sniper_HeadshotStuns = 119
    kKillEaterEvent_EarthSpirit_SmashStuns = 120
    kKillEaterEvent_EarthSpirit_GripSilences = 121
    kKillEaterEvent_ShadowShaman_ShackleKills = 122
    kKillEaterEvent_ShadowShaman_HexKills = 123
    kKillEaterEvent_Centaur_EnemiesStomped = 124
    kKillEaterEvent_Centaur_DoubleEdgeKills = 125
    kKillEaterEvent_Centaur_ReturnKills = 126
    kKillEaterEvent_EmberSpirit_EnemiesChained = 127
    kKillEaterEvent_EmberSpirit_SleightOfFistMultiKills = 128
    kKillEaterEvent_Puck_OrbKills = 129
    kKillEaterEvent_VengefulSpirit_EnemiesStunned = 130
    kKillEaterEvent_Lifestealer_RageKills = 131
    kKillEaterEvent_Lifestealer_OpenWoundsKills = 132
    kKillEaterEvent_Lifestealer_InfestKills = 133
    kKillEaterEvent_ElderTitan_SpiritKills = 134
    kKillEaterEvent_ElderTitan_GoodStomps = 135
    kKillEaterEvent_Clockwerk_RocketKills = 136
    kKillEaterEvent_Clockwerk_BlindRocketKills = 137
    kKillEaterEvent_StormSpirit_BallKills = 138
    kKillEaterEvent_StormSpirit_DoubleRemnantKills = 139
    kKillEaterEvent_StormSpirit_VortexKills = 140
    kKillEaterEvent_Tinker_DoubleMissileKills = 141
    kKillEaterEvent_Tinker_LaserKills = 142
    kKillEaterEvent_Techies_SuicideKills = 143
    kKillEaterEvent_Techies_LandMineKills = 144
    kKillEaterEvent_Techies_StatisTrapStuns = 145
    kKillEaterEvent_Techies_RemoteMineKills = 146
    kKillEaterEvent_ShadowFiend_TripleRazeKills = 147
    kKillEaterEvent_ShadowFiend_RequiemMultiKills = 148
    kKillEaterEvent_ShadowFiend_QRazeKills = 149
    kKillEaterEvent_ShadowFiend_WRazeKills = 150
    kKillEaterEvent_ShadowFiend_ERazeKills = 151
    kKillEaterEvent_Oracle_FatesEdictKills = 152
    kKillEaterEvent_Oracle_FalsePromiseSaves = 153
    kKillEaterEvent_Juggernaut_OmnislashKills = 154
    kKillEaterEventType_SkeletonKing_SkeletonHeroKills = 157
    kKillEaterEventType_DarkWillow_CursedCrownTripleStuns = 158
    kKillEaterEventType_Dazzle_ShallowGraveSaves = 159
    kKillEaterEventType_Dazzle_PoisonTouchKills = 160
    kKillEaterEventType_ThreeManMeks = 161
    kKillEaterEventType_Viper_PoisonAttackKills = 162
    kKillEaterEventType_Viper_CorrosiveSkinKills = 163
    kKillEaterEventType_ThreeHeroVeils = 164
    kKillEaterEventType_Viper_KillsDuringViperStrike = 165
    kKillEaterEventType_SolarCrestKills = 166
    kKillEaterEventType_Tiny_TreeThrowKills = 167
    kKillEaterEventType_Riki_BackstabKills = 168
    kKillEaterEventType_Phoenix_ThreeHeroSupernovaStuns = 169
    kKillEaterEventType_Terrorblade_MetamorphosisKills = 170
    kKillEaterEventType_Lion_GreatFingerKills = 171
    kKillEaterEventType_Antimage_SpellsBlockedWithAghanims = 172
    kKillEaterEventType_Antimage_ThreeManManaVoids = 173
    kKillEaterEventType_ArcWarden_TempestDoubleKills = 174
    kKillEaterEventType_ArcWarden_SparkWraithKills = 175
    kKillEaterEventType_Bane_BrainSapKills = 176
    kKillEaterEventType_Bane_FiendsGripKills = 177
    kKillEaterEventType_Batrider_TripleHeroFlamebreaks = 178
    kKillEaterEventType_Batrider_DoubleHeroLassoes = 179
    kKillEaterEventType_Brewmaster_KillsDuringPrimalSplit = 180
    kKillEaterEventType_Bristleback_KillsUnderFourQuillStacks = 181
    kKillEaterEventType_Bristleback_TripleHeroNasalGoo = 182
    kKillEaterEventType_Broodmother_SpiderlingHeroKills = 183
    kKillEaterEventType_Broodmother_KillsInsideWeb = 184
    kKillEaterEventType_Centaur_ThreeHeroStampede = 185
    kKillEaterEventType_ChaosKnight_RealityRiftKills = 186
    kKillEaterEventType_Chen_KillsWithPenitence = 187
    kKillEaterEventType_CrystalMaiden_TwoHeroCrystalNovas = 188
    kKillEaterEventType_CrystalMaiden_ThreeHeroFreezingFields = 189
    kKillEaterEventType_Dazzle_ShadowWaveKills = 190
    kKillEaterEventType_DeathProphet_SiphonKills = 191
    kKillEaterEventType_DeathProphet_ExorcismKillsDuringEuls = 192
    kKillEaterEventType_Disruptor_ThreeHeroKineticFieldStaticStorm = 193
    kKillEaterEventType_Doom_InfernalBladeBurnKills = 194
    kKillEaterEventType_DrowRanger_PrecisionAuraCreepTowerKills = 195
    kKillEaterEventType_EmberSpirit_RemnantKills = 196
    kKillEaterEventType_EmberSpirit_SleightOfFistKills = 197
    kKillEaterEventType_Enigma_MidnightPulseBlackHoleCombos = 198
    kKillEaterEventType_Enigma_ThreeManBlackHoles = 199
    kKillEaterEventType_FacelessVoid_MultiHeroTimeDilation = 200
    kKillEaterEventType_Gyrocopter_ThreeHeroFlakCannon = 201
    kKillEaterEventType_Gyrocopter_HomingMissileKills = 202
    kKillEaterEventType_Gyrocopter_RocketBarrageKills = 203
    kKillEaterEventType_Huskar_KillsDuringLifeBreak = 204
    kKillEaterEventType_Huskar_BurningSpearKills = 205
    kKillEaterEventType_Invoker_MultiHeroIceWall = 206
    kKillEaterEventType_Invoker_ThreeHeroEMP = 207
    kKillEaterEventType_Invoker_ThreeHeroDeafeningBlast = 208
    kKillEaterEventType_Invoker_MultiHeroChaosMeteor = 209
    kKillEaterEventType_Jakiro_MultiHeroDualBreath = 210
    kKillEaterEventType_Jakiro_IcePathMacropyreCombos = 211
    kKillEaterEventType_Leshrac_PulseNovaKills = 212
    kKillEaterEventType_Leshrac_ThreeHeroLightningStorm = 213
    kKillEaterEventType_Lion_ThreeHeroFingerOfDeath = 214
    kKillEaterEventType_Meepo_PoofKills = 215
    kKillEaterEventType_Meepo_MultiHeroEarthbinds = 216
    kKillEaterEventType_NightStalker_NighttimeKills = 217
    kKillEaterEventType_Morphling_KillsDuringReplicate = 218
    kKillEaterEventType_OgreMagi_FireblastKills = 219
    kKillEaterEventType_OgreMagi_IgniteKills = 220
    kKillEaterEventType_DominatingKillStreaks = 221
    kKillEaterEventType_MegaKillStreaks = 222
    kKillEaterEventType_Alchemist_AghanimsGiven = 223
    kKillEaterEventType_VeilsLeadingToKills = 224
    kKillEaterEventType_DustLeadingToKills = 225
    kKillEaterEventType_WitchDoctor_MultiHeroCaskStuns = 226
    kKillEaterEventType_Weaver_ShukuchiKills = 227
    kKillEaterEventType_Windrunner_ShackleFocusFireKills = 228
    kKillEaterEventType_VengefulSpirit_VengeanceAuraIllusionKills = 229
    kKillEaterEventType_Tusk_WalrusPunchKills = 230
    kKillEaterEventType_Tinker_TripleHeroLasers = 231
    kKillEaterEventType_TemplarAssassin_MultiHeroPsiBlades = 232
    kKillEaterEventType_Sven_KillsDuringGodsStrength = 233
    kKillEaterEventType_Sniper_ThreeHeroShrapnels = 234
    kKillEaterEventType_Slark_KillsDuringShadowDance = 235
    kKillEaterEventType_ShadowShaman_MultiHeroEtherShocks = 236
    kKillEaterEventType_ShadowShaman_SerpentWardShackleKills = 237
    kKillEaterEventType_Riki_ThreeHeroTricksOfTheTrade = 238
    kKillEaterEventType_Razor_EyeOfTheStormKills = 239
    kKillEaterEventType_Pugna_LifeDrainKills = 240
    kKillEaterEventType_ObsidianDestroyer_SanitysEclipseKills = 241
    kKillEaterEventType_Oracle_MultiHeroFortunesEnd = 242
    kKillEaterEventType_Omniknight_PurificationKills = 243
    kKillEaterEventType_NightStalker_EnemyMissesUnderCripplingFear = 244
    kKillEaterEventType_Warlock_ThreeHeroFatalBonds = 245
    kKillEaterEventType_Riki_TricksOfTheTradeKills = 246
    kKillEaterEventType_Earthshaker_AftershockHits10 = 247
    kKillEaterEventType_Earthshaker_5HeroEchoslams = 248
    kKillEaterEventType_Lina_LagunaBladeHeroKills = 249
    kKillEaterEventType_Lina_LightStrikeHeroStuns = 250
    kKillEaterEventType_Earthshaker_FissureMultiStuns = 251
    kKillEaterEventType_Earthshaker_TotemKills = 252
    kKillEaterEventType_Pangolier_SwashbuckleKills = 253
    kKillEaterEventType_Furion_EnemyHeroesTrapped = 254
    kKillEaterEventType_Pangolier_HeartpiercerKills = 255
    kKillEaterEventType_Medusa_MultiHeroStoneGaze = 256
    kKillEaterEventType_Medusa_SplitShotKills = 257
    kKillEaterEventType_Mirana_MultiHeroStarstorm = 258
    kKillEaterEventType_Mirana_KillsFromMoonlightShadow = 259
    kKillEaterEventType_Magnus_MultiHeroSkewers = 260
    kKillEaterEventType_Magnus_MultiHeroReversePolarity = 261
    kKillEaterEventType_Magnus_HeroesSlowedWithShockwave = 262
    kKillEaterEventType_NagaSiren_MultiHeroSong = 263
    kKillEaterEventType_NagaSiren_AlliesHealedBySong = 264
    kKillEaterEventType_LoneDruid_MultiHeroRoar = 265
    kKillEaterEventType_LoneDruid_BattleCryKills = 266
    kKillEaterEventType_WinterWyvern_ThreeHeroCurses = 267
    kKillEaterEventType_Antimage_SpellsBlockedWithCounterspell = 268
    kKillEaterEventType_Mars_EnemiesKilledInArena = 269
    kKillEaterEventType_Mars_MultiHeroGodsRebuke = 270
    kKillEaterEventType_Mars_GodsRebukeKills = 271
    kKillEaterEventType_Snapfire_LizardBlobsKills = 272
    kKillEaterEventType_Snapfire_TwoHeroCookieStuns = 273
    Custom_KillStreak = 274


@dataclass
class CSODOTAPartyMember(betterproto.Message):
    partner_type: "PartnerAccountType" = betterproto.enum_field(1)
    is_coach: bool = betterproto.bool_field(2)
    region_ping_codes: List[int] = betterproto.uint32_field(4)
    region_ping_times: List[int] = betterproto.uint32_field(5)
    region_ping_failed_bitmask: int = betterproto.uint32_field(6)
    is_plus_subscriber: bool = betterproto.bool_field(10)
    tourney_skill_level: int = betterproto.uint32_field(7)
    tourney_buyin: int = betterproto.uint32_field(8)
    tourney_prevent_until: int = betterproto.uint32_field(9)
    mm_data_valid: bool = betterproto.bool_field(13)
    lane_selection_flags: int = betterproto.uint32_field(11)
    high_priority_disabled: bool = betterproto.bool_field(14)
    has_hp_resource: bool = betterproto.bool_field(15)
    joined_from_partyfinder: bool = betterproto.bool_field(12)


@dataclass
class CSODOTAParty(betterproto.Message):
    party_id: int = betterproto.uint64_field(1)
    leader_id: float = betterproto.fixed64_field(2)
    member_ids: List[float] = betterproto.fixed64_field(3)
    game_modes: int = betterproto.uint32_field(4)
    state: "CSODOTAPartyState" = betterproto.enum_field(6)
    effective_started_matchmaking_time: int = betterproto.uint32_field(7)
    raw_started_matchmaking_time: int = betterproto.uint32_field(32)
    attempt_start_time: int = betterproto.uint32_field(33)
    attempt_num: int = betterproto.uint32_field(34)
    matchgroups: int = betterproto.uint32_field(11)
    low_priority_account_id: int = betterproto.uint32_field(19)
    match_type: "MatchType" = betterproto.enum_field(21)
    bot_difficulty: "DOTABotDifficulty" = betterproto.enum_field(22)
    team_id: int = betterproto.uint32_field(23)
    team_name: str = betterproto.string_field(51)
    team_ui_logo: int = betterproto.uint64_field(52)
    team_base_logo: int = betterproto.uint64_field(53)
    match_disabled_until_date: int = betterproto.uint32_field(24)
    match_disabled_account_id: int = betterproto.uint32_field(25)
    matchmaking_max_range_minutes: int = betterproto.uint32_field(26)
    matchlanguages: int = betterproto.uint32_field(27)
    members: List["CSODOTAPartyMember"] = betterproto.message_field(29)
    low_priority_games_remaining: int = betterproto.uint32_field(35)
    open_for_join_requests: bool = betterproto.bool_field(40)
    sent_invites: List["CSODOTAPartyInvite"] = betterproto.message_field(41)
    recv_invites: List["CSODOTAPartyInvite"] = betterproto.message_field(42)
    account_flags: int = betterproto.uint32_field(43)
    region_select_flags: int = betterproto.uint32_field(44)
    exclusive_tournament_id: int = betterproto.uint32_field(45)
    tourney_division_id: int = betterproto.uint32_field(47)
    tourney_schedule_time: int = betterproto.uint32_field(48)
    tourney_skill_level: int = betterproto.uint32_field(49)
    tourney_bracket_round: int = betterproto.uint32_field(50)
    tourney_queue_deadline_time: int = betterproto.uint32_field(54)
    tourney_queue_deadline_state: "ETourneyQueueDeadlineState" = betterproto.enum_field(
        55
    )
    party_builder_slots_to_fill: int = betterproto.uint32_field(56)
    party_builder_match_groups: int = betterproto.uint32_field(57)
    party_builder_start_time: int = betterproto.uint32_field(58)
    solo_queue: bool = betterproto.bool_field(59)
    bot_script_index: int = betterproto.uint32_field(60)
    steam_clan_account_id: int = betterproto.uint32_field(61)
    ready_check: "CMsgReadyCheckStatus" = betterproto.message_field(62)
    custom_game_disabled_until_date: int = betterproto.uint32_field(63)
    custom_game_disabled_account_id: int = betterproto.uint32_field(64)
    is_challenge_match: bool = betterproto.bool_field(65)
    party_search_beacon_active: bool = betterproto.bool_field(66)
    matchmaking_flags: int = betterproto.uint32_field(67)
    high_priority_state: "EHighPriorityMMState" = betterproto.enum_field(68)
    lane_selections_enabled: bool = betterproto.bool_field(69)
    custom_game_difficulty_mask: int = betterproto.uint32_field(70)


@dataclass
class CSODOTAPartyInvite(betterproto.Message):
    group_id: int = betterproto.uint64_field(1)
    sender_id: float = betterproto.fixed64_field(2)
    sender_name: str = betterproto.string_field(3)
    members: List["CSODOTAPartyInvitePartyMember"] = betterproto.message_field(4)
    team_id: int = betterproto.uint32_field(5)
    low_priority_status: bool = betterproto.bool_field(6)
    as_coach: bool = betterproto.bool_field(7)
    invite_gid: float = betterproto.fixed64_field(8)


@dataclass
class CSODOTAPartyInvitePartyMember(betterproto.Message):
    name: str = betterproto.string_field(1)
    steam_id: float = betterproto.fixed64_field(2)
    is_coach: bool = betterproto.bool_field(4)


@dataclass
class CSODOTALobbyInvite(betterproto.Message):
    group_id: int = betterproto.uint64_field(1)
    sender_id: float = betterproto.fixed64_field(2)
    sender_name: str = betterproto.string_field(3)
    members: List["CSODOTALobbyInviteLobbyMember"] = betterproto.message_field(4)
    custom_game_id: int = betterproto.uint64_field(5)
    invite_gid: float = betterproto.fixed64_field(6)
    custom_game_crc: float = betterproto.fixed64_field(7)
    custom_game_timestamp: float = betterproto.fixed32_field(8)


@dataclass
class CSODOTALobbyInviteLobbyMember(betterproto.Message):
    name: str = betterproto.string_field(1)
    steam_id: float = betterproto.fixed64_field(2)


@dataclass
class CMsgLeaverState(betterproto.Message):
    lobby_state: int = betterproto.uint32_field(1)
    game_state: "DOTA_GameState" = betterproto.enum_field(2)
    leaver_detected: bool = betterproto.bool_field(3)
    first_blood_happened: bool = betterproto.bool_field(4)
    discard_match_results: bool = betterproto.bool_field(5)
    mass_disconnect: bool = betterproto.bool_field(6)


@dataclass
class CSODOTALobbyMember(betterproto.Message):
    id: float = betterproto.fixed64_field(1)
    hero_id: int = betterproto.uint32_field(2)
    team: "DOTA_GC_TEAM" = betterproto.enum_field(3)
    name: str = betterproto.string_field(6)
    slot: int = betterproto.uint32_field(7)
    party_id: int = betterproto.uint64_field(12)
    meta_level: int = betterproto.uint32_field(13)
    meta_xp: int = betterproto.uint32_field(14)
    meta_xp_awarded: int = betterproto.uint32_field(15)
    leaver_status: "DOTALeaverStatusT" = betterproto.enum_field(16)
    leaver_actions: int = betterproto.uint32_field(28)
    channel: int = betterproto.uint32_field(17)
    disabled_hero_id: List[int] = betterproto.uint32_field(20)
    partner_account_type: "PartnerAccountType" = betterproto.enum_field(21)
    enabled_hero_id: List[int] = betterproto.uint32_field(22)
    coach_team: "DOTA_GC_TEAM" = betterproto.enum_field(23)
    coach_rating: int = betterproto.uint32_field(42)
    pwrd_cyber_cafe_id: int = betterproto.uint32_field(24)
    pwrd_cyber_cafe_name: str = betterproto.string_field(25)
    disabled_random_hero_bits: List[float] = betterproto.fixed32_field(41)
    rank_change: int = betterproto.sint32_field(29)
    cameraman: bool = betterproto.bool_field(30)
    custom_game_product_ids: List[int] = betterproto.uint32_field(31)
    search_match_type: "MatchType" = betterproto.enum_field(33)
    favorite_team_packed: int = betterproto.uint64_field(35)
    is_plus_subscriber: bool = betterproto.bool_field(36)
    rank_tier_updated: bool = betterproto.bool_field(37)
    lane_selection_flags: int = betterproto.uint32_field(38)
    can_earn_rewards: bool = betterproto.bool_field(39)
    live_spectator_team: "DOTA_GC_TEAM" = betterproto.enum_field(40)
    was_mvp_last_game: bool = betterproto.bool_field(43)
    pending_awards: List["CMsgPendingEventAward"] = betterproto.message_field(44)
    pending_awards_on_victory: List[
        "CMsgPendingEventAward"
    ] = betterproto.message_field(45)
    rank_mmr_boost_type: "EDOTAMMRBoostType" = betterproto.enum_field(46)
    queue_point_adjustment: int = betterproto.sint32_field(47)
    rank_tier: int = betterproto.int32_field(48)
    title: int = betterproto.uint32_field(50)
    guild_id: int = betterproto.uint32_field(51)


@dataclass
class CLobbyTeamDetails(betterproto.Message):
    team_name: str = betterproto.string_field(1)
    team_tag: str = betterproto.string_field(3)
    team_id: int = betterproto.uint32_field(4)
    team_logo: int = betterproto.uint64_field(5)
    team_base_logo: int = betterproto.uint64_field(6)
    team_banner_logo: int = betterproto.uint64_field(7)
    team_complete: bool = betterproto.bool_field(8)
    rank: int = betterproto.uint32_field(15)
    rank_change: int = betterproto.sint32_field(16)
    is_home_team: bool = betterproto.bool_field(17)
    is_challenge_match: bool = betterproto.bool_field(18)
    challenge_match_token_account: int = betterproto.uint64_field(19)
    team_logo_url: str = betterproto.string_field(20)


@dataclass
class CLobbyGuildDetails(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    guild_primary_color: int = betterproto.uint32_field(2)
    guild_secondary_color: int = betterproto.uint32_field(3)
    guild_pattern: int = betterproto.uint32_field(4)
    guild_logo: int = betterproto.uint64_field(5)
    guild_points: int = betterproto.uint32_field(6)
    guild_event: int = betterproto.uint32_field(7)
    guild_flags: int = betterproto.uint32_field(8)
    team_for_guild: "DOTA_GC_TEAM" = betterproto.enum_field(9)
    guild_tag: str = betterproto.string_field(10)


@dataclass
class CLobbyTimedRewardDetails(betterproto.Message):
    item_def_index: int = betterproto.uint32_field(2)
    is_supply_crate: bool = betterproto.bool_field(3)
    is_timed_drop: bool = betterproto.bool_field(4)
    account_id: int = betterproto.uint32_field(5)
    origin: int = betterproto.uint32_field(6)


@dataclass
class CLobbyBroadcastChannelInfo(betterproto.Message):
    channel_id: int = betterproto.uint32_field(1)
    country_code: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)
    language_code: str = betterproto.string_field(4)


@dataclass
class CLobbyGuildChallenge(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    event_id: "EEvent" = betterproto.enum_field(2)
    challenge_instance_id: int = betterproto.uint32_field(3)
    challenge_parameter: int = betterproto.uint32_field(4)
    challenge_timestamp: int = betterproto.uint32_field(5)
    challenge_period_serial: int = betterproto.uint32_field(6)
    challenge_progress_at_start: int = betterproto.uint32_field(7)
    eligible_account_ids: List[int] = betterproto.uint32_field(8)


@dataclass
class CSODOTALobby(betterproto.Message):
    lobby_id: int = betterproto.uint64_field(1)
    members: List["CSODOTALobbyMember"] = betterproto.message_field(2)
    left_members: List["CSODOTALobbyMember"] = betterproto.message_field(7)
    leader_id: float = betterproto.fixed64_field(11)
    server_id: float = betterproto.fixed64_field(6)
    game_mode: int = betterproto.uint32_field(3)
    pending_invites: List[float] = betterproto.fixed64_field(10)
    state: "CSODOTALobbyState" = betterproto.enum_field(4)
    connect: str = betterproto.string_field(5)
    lobby_type: "CSODOTALobbyLobbyType" = betterproto.enum_field(12)
    allow_cheats: bool = betterproto.bool_field(13)
    fill_with_bots: bool = betterproto.bool_field(14)
    intro_mode: bool = betterproto.bool_field(15)
    game_name: str = betterproto.string_field(16)
    team_details: List["CLobbyTeamDetails"] = betterproto.message_field(17)
    tutorial_lesson: int = betterproto.uint32_field(18)
    tournament_id: int = betterproto.uint32_field(19)
    tournament_game_id: int = betterproto.uint32_field(20)
    server_region: int = betterproto.uint32_field(21)
    game_state: "DOTA_GameState" = betterproto.enum_field(22)
    num_spectators: int = betterproto.uint32_field(23)
    matchgroup: int = betterproto.uint32_field(25)
    cm_pick: "DOTA_CM_PICK" = betterproto.enum_field(28)
    match_id: int = betterproto.uint64_field(30)
    allow_spectating: bool = betterproto.bool_field(31)
    bot_difficulty_radiant: "DOTABotDifficulty" = betterproto.enum_field(36)
    game_version: "DOTAGameVersion" = betterproto.enum_field(37)
    timed_reward_details: List["CLobbyTimedRewardDetails"] = betterproto.message_field(
        38
    )
    pass_key: str = betterproto.string_field(39)
    leagueid: int = betterproto.uint32_field(42)
    penalty_level_radiant: int = betterproto.uint32_field(43)
    penalty_level_dire: int = betterproto.uint32_field(44)
    load_game_id: int = betterproto.uint32_field(45)
    series_type: int = betterproto.uint32_field(46)
    radiant_series_wins: int = betterproto.uint32_field(47)
    dire_series_wins: int = betterproto.uint32_field(48)
    loot_generated: int = betterproto.uint32_field(49)
    loot_awarded: int = betterproto.uint32_field(50)
    allchat: bool = betterproto.bool_field(51)
    dota_tv_delay: "LobbyDotaTVDelay" = betterproto.enum_field(53)
    custom_game_mode: str = betterproto.string_field(54)
    custom_map_name: str = betterproto.string_field(55)
    custom_difficulty: int = betterproto.uint32_field(56)
    lan: bool = betterproto.bool_field(57)
    broadcast_channel_info: List[
        "CLobbyBroadcastChannelInfo"
    ] = betterproto.message_field(58)
    first_leaver_accountid: int = betterproto.uint32_field(59)
    series_id: int = betterproto.uint32_field(60)
    low_priority: bool = betterproto.bool_field(61)
    extra_messages: List["CSODOTALobbyCExtraMsg"] = betterproto.message_field(62)
    save_game: "CDOTASaveGame" = betterproto.message_field(63)
    first_blood_happened: bool = betterproto.bool_field(65)
    match_outcome: "EMatchOutcome" = betterproto.enum_field(70)
    mass_disconnect: bool = betterproto.bool_field(67)
    custom_game_id: int = betterproto.uint64_field(68)
    custom_min_players: int = betterproto.uint32_field(71)
    custom_max_players: int = betterproto.uint32_field(72)
    partner_type: "PartnerAccountType" = betterproto.enum_field(73)
    visibility: "DOTALobbyVisibility" = betterproto.enum_field(75)
    custom_game_crc: float = betterproto.fixed64_field(76)
    custom_game_auto_created_lobby: bool = betterproto.bool_field(77)
    custom_game_timestamp: float = betterproto.fixed32_field(80)
    previous_series_matches: List[int] = betterproto.uint64_field(81)
    previous_match_override: int = betterproto.uint64_field(82)
    custom_game_uses_account_records: bool = betterproto.bool_field(83)
    game_start_time: int = betterproto.uint32_field(87)
    pause_setting: "LobbyDotaPauseSetting" = betterproto.enum_field(88)
    lobby_mvp_account_id: int = betterproto.uint32_field(89)
    weekend_tourney_division_id: int = betterproto.uint32_field(90)
    weekend_tourney_skill_level: int = betterproto.uint32_field(91)
    weekend_tourney_bracket_round: int = betterproto.uint32_field(92)
    bot_difficulty_dire: "DOTABotDifficulty" = betterproto.enum_field(93)
    bot_radiant: int = betterproto.uint64_field(94)
    bot_dire: int = betterproto.uint64_field(95)
    event_progression_enabled: List["EEvent"] = betterproto.enum_field(96)
    selection_priority_rules: "DOTASelectionPriorityRules" = betterproto.enum_field(97)
    series_previous_selection_priority_team_id: int = betterproto.uint32_field(98)
    series_current_selection_priority_team_id: int = betterproto.uint32_field(99)
    series_current_priority_team_choice: "DOTASelectionPriorityChoice" = (
        betterproto.enum_field(100)
    )
    series_current_non_priority_team_choice: "DOTASelectionPriorityChoice" = (
        betterproto.enum_field(101)
    )
    series_current_selection_priority_used_coin_toss: bool = betterproto.bool_field(102)
    current_primary_event: "EEvent" = betterproto.enum_field(103)
    emergency_disabled_hero_ids: List[int] = betterproto.uint32_field(105)
    custom_game_private_key: float = betterproto.fixed64_field(106)
    custom_game_penalties: bool = betterproto.bool_field(107)
    lan_host_ping_location: str = betterproto.string_field(109)
    league_node_id: int = betterproto.uint32_field(110)
    match_duration: int = betterproto.uint32_field(111)
    custom_game_browseable: bool = betterproto.bool_field(112)
    league_phase: int = betterproto.uint32_field(113)
    record_detailed_stats: bool = betterproto.bool_field(114)
    experimental_gameplay_enabled: bool = betterproto.bool_field(116)
    guild_challenges: List["CLobbyGuildChallenge"] = betterproto.message_field(117)
    guild_details: List["CLobbyGuildDetails"] = betterproto.message_field(118)
    lobby_event_points: List["CMsgLobbyEventPoints"] = betterproto.message_field(119)


@dataclass
class CSODOTALobbyCExtraMsg(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    contents: bytes = betterproto.bytes_field(2)


@dataclass
class CMsgLobbyPlaytestDetails(betterproto.Message):
    json: str = betterproto.string_field(1)


@dataclass
class CMsgReadyCheckStatus(betterproto.Message):
    start_timestamp: int = betterproto.uint32_field(1)
    finish_timestamp: int = betterproto.uint32_field(2)
    initiator_account_id: int = betterproto.uint32_field(3)
    ready_members: List["CMsgReadyCheckStatusReadyMember"] = betterproto.message_field(
        4
    )


@dataclass
class CMsgReadyCheckStatusReadyMember(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    ready_status: "EReadyCheckStatus" = betterproto.enum_field(2)


@dataclass
class CMsgPartyReadyCheckRequest(betterproto.Message):
    pass


@dataclass
class CMsgPartyReadyCheckResponse(betterproto.Message):
    result: "EReadyCheckRequestResult" = betterproto.enum_field(1)


@dataclass
class CMsgPartyReadyCheckAcknowledge(betterproto.Message):
    ready_status: "EReadyCheckStatus" = betterproto.enum_field(1)


@dataclass
class CMsgLobbyEventGameDetails(betterproto.Message):
    kv_data: bytes = betterproto.bytes_field(1)


@dataclass
class CMsgMatchMatchmakingStats(betterproto.Message):
    average_queue_time: int = betterproto.uint32_field(1)
    maximum_queue_time: int = betterproto.uint32_field(2)
    behavior_score_variance: "EMatchBehaviorScoreVariance" = betterproto.enum_field(3)


@dataclass
class CMvpData(betterproto.Message):
    mvps: List["CMvpDataMvpDatum"] = betterproto.message_field(1)


@dataclass
class CMvpDataMvpDatum(betterproto.Message):
    slot: int = betterproto.uint32_field(1)
    accolades: List["CMvpDataMvpDatumMvpAccolade"] = betterproto.message_field(2)
    account_id: int = betterproto.uint32_field(3)


@dataclass
class CMvpDataCMvpDataMvpDatumMvpAccolade(betterproto.Message):
    type: "CMvpDataMvpDatumMvpAccoladeMvpAccoladeType" = betterproto.enum_field(1)
    detail_value: float = betterproto.float_field(2)
