# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_gcmessages_client_guild_events.proto
# plugin: python-betterproto

from dataclasses import dataclass
from typing import List

import betterproto

from .dota_shared_enums import EEvent


class EGuildEventAuditAction(betterproto.Enum):
    Invalid = 0
    DevGrant = 1
    CompleteContract = 2
    CompleteChallenge = 3
    CompleteMatchWinner = 4
    ChallengeProgress = 5
    CompleteMatchLoser = 6


class CMsgClientToGCRequestAccountGuildEventDataResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidEvent = 5
    InvalidGuild = 6
    NotMember = 7
    InvalidGuildEvent = 8


class CMsgClientToGCRequestActiveGuildContractsResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidEvent = 5
    InvalidGuild = 6
    NotMember = 7
    InvalidGuildEvent = 8


class CMsgClientToGCSelectGuildContractResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidEvent = 5
    InvalidGuild = 6
    NotMember = 7
    InvalidGuildEvent = 8
    InvalidContractID = 9
    AlreadyAssigned = 10
    InvalidContractSlot = 11
    ContractSlotLocked = 12
    ContractSlotCooldown = 13
    ContractDuplicate = 14
    ContractSlotTimeError = 15


class CMsgClientToGCRequestActiveGuildChallengeResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidEvent = 5
    InvalidGuild = 6
    NotMember = 7
    InvalidGuildEvent = 8


class CMsgClientToGCRequestGuildEventMembersResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidEvent = 5
    InvalidGuild = 6
    NotMember = 7
    InvalidGuildEvent = 8


@dataclass(eq=False, repr=False)
class CMsgGuildContract(betterproto.Message):
    contract_id: int = betterproto.uint64_field(1)
    challenge_instance_id: int = betterproto.uint32_field(2)
    challenge_parameter: int = betterproto.uint32_field(3)
    challenge_timestamp: int = betterproto.uint32_field(4)
    assigned_account_id: int = betterproto.uint32_field(5)
    contract_flags: int = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class CMsgGuildContractSlot(betterproto.Message):
    contract: "CMsgGuildContract" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CMsgAccountGuildEventData(betterproto.Message):
    guild_points: int = betterproto.uint32_field(1)
    contracts_refreshed_timestamp: int = betterproto.uint32_field(2)
    contract_slots: List["CMsgGuildContractSlot"] = betterproto.message_field(3)
    completed_challenge_count: int = betterproto.uint32_field(4)
    challenges_refresh_timestamp: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class CMsgGuildActiveContracts(betterproto.Message):
    contracts_refreshed_timestamp: int = betterproto.uint32_field(1)
    contracts: List["CMsgGuildContract"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CMsgGuildChallenge(betterproto.Message):
    challenge_instance_id: int = betterproto.uint32_field(1)
    challenge_parameter: int = betterproto.uint32_field(2)
    challenge_timestamp: int = betterproto.uint32_field(3)
    challenge_progress: int = betterproto.uint32_field(4)
    challenge_flags: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class CMsgGuildEventMember(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    guild_points_earned: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGCRequestAccountGuildEventData(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    event_id: "EEvent" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGCRequestAccountGuildEventDataResponse(betterproto.Message):
    result: "CMsgClientToGCRequestAccountGuildEventDataResponseEResponse" = (
        betterproto.enum_field(1)
    )
    event_id: "EEvent" = betterproto.enum_field(2)
    event_data: "CMsgAccountGuildEventData" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class CMsgGCToClientAccountGuildEventDataUpdated(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    event_id: "EEvent" = betterproto.enum_field(2)
    update_flags: int = betterproto.uint32_field(3)
    guild_event_data: "CMsgAccountGuildEventData" = betterproto.message_field(4)
    contracts_updated: bool = betterproto.bool_field(5)


@dataclass(eq=False, repr=False)
class CMsgClientToGCRequestActiveGuildContracts(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    event_id: "EEvent" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGCRequestActiveGuildContractsResponse(betterproto.Message):
    result: "CMsgClientToGCRequestActiveGuildContractsResponseEResponse" = (
        betterproto.enum_field(1)
    )
    active_contracts: "CMsgGuildActiveContracts" = betterproto.message_field(2)
    active_challenges: "CMsgGuildChallenge" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class CMsgGCToClientActiveGuildContractsUpdated(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    event_id: "EEvent" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGCSelectGuildContract(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    event_id: "EEvent" = betterproto.enum_field(2)
    contract_id: int = betterproto.uint64_field(3)
    contract_slot: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CMsgClientToGCSelectGuildContractResponse(betterproto.Message):
    result: "CMsgClientToGCSelectGuildContractResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass(eq=False, repr=False)
class CMsgClientToGCRequestActiveGuildChallenge(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    event_id: "EEvent" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGCRequestActiveGuildChallengeResponse(betterproto.Message):
    result: "CMsgClientToGCRequestActiveGuildChallengeResponseEResponse" = (
        betterproto.enum_field(1)
    )
    active_challenge: "CMsgGuildChallenge" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CMsgGCToClientActiveGuildChallengeUpdated(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    event_id: "EEvent" = betterproto.enum_field(2)
    active_challenge: "CMsgGuildChallenge" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class CMsgClientToGCRequestGuildEventMembers(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    event_id: "EEvent" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGCRequestGuildEventMembersResponse(betterproto.Message):
    result: "CMsgClientToGCRequestGuildEventMembersResponseEResponse" = (
        betterproto.enum_field(1)
    )
    members: List["CMsgGuildEventMember"] = betterproto.message_field(2)
