# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_gcmessages_client_guild.proto
# plugin: python-betterproto

from dataclasses import dataclass
from typing import List

import betterproto


class EGuildAuditAction(betterproto.Enum):
    Invalid = 0
    GuildCreated = 1
    GuildLanguageChanged = 2
    GuildFlagsChanged = 3
    GuildMemberJoined = 5
    GuildMemberLeft = 6
    GuildMemberKicked = 7
    GuildMemberRoleChanged = 8
    GuildLogoChanged = 9
    GuildRegionChanged = 10
    GuildDescriptionChanged = 11
    GuildPrimaryColorChanged = 12
    GuildSecondaryColorChanged = 13
    GuildPatternChanged = 14
    AdminClearedLogo = 15
    GuildRequiredRankChanged = 16
    GuildMotDChanged = 18
    AdminResetName = 19
    AdminResetTag = 20
    AdminLock = 21
    GuildNameChanged = 22
    GuildTagChanged = 23
    AdminPermitted = 24
    AdminBlocked = 25
    AdminBannedUser = 26


class EGuildChatType(betterproto.Enum):
    Unspecified = 0
    SteamChatGroup = 1
    GC = 2


class CMsgClientToGCCreateGuildResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidName = 5
    NameAlreadyUsed = 6
    InvalidTag = 7
    TagAlreadyUsed = 8
    InvalidDescription = 9
    InvalidRegion = 10
    InvalidLogo = 11
    DoesNotOwnEvent = 12
    GuildLimit = 13
    InvalidMotD = 14
    Blocked = 15


class CMsgClientToGCSetGuildInfoResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    NotMember = 6
    NoPermission = 7
    MotDTooLong = 8
    NameChangeNoPermissions = 9
    TagChangeNoPermissions = 10
    NameInvalid = 11
    TagInvalid = 12
    DescriptionInvalid = 13
    Blocked = 14


class CMsgClientToGCRequestGuildDataResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    NotMember = 6


class CMsgClientToGCRequestGuildMembershipResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4


class CMsgClientToGCRequestGuildSummaryResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5


class CMsgClientToGCJoinGuildResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    GuildFull = 6
    AlreadyMember = 7
    GuildLimit = 8
    GuildRequiresInvite = 9
    GuildRankTooLow = 10


class CMsgClientToGCLeaveGuildResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    NotMember = 6
    LastAdmin = 7


class CMsgClientToGCKickGuildMemberResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    RequesterNotMember = 6
    TargetNotMember = 7
    NoPermission = 8
    CantKickSelf = 9


class CMsgClientToGCSetGuildMemberRoleResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    RequesterNotMember = 6
    TargetNotMember = 7
    NoPermission = 8
    InvalidRole = 9
    AdminViolation = 10


class CMsgClientToGCInviteToGuildResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    GuildFull = 6
    RequesterNotMember = 7
    AlreadyAMember = 8
    AlreadyInvited = 9
    NoInvitePermissions = 10
    TooManyInvites = 11


class CMsgClientToGCDeclineInviteToGuildResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    NoInviteFound = 6


class CMsgClientToGCAcceptInviteToGuildResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    NoInviteFound = 6
    GuildFull = 7
    GuildLimit = 8
    InvalidInviter = 9
    AlreadyInGuild = 10


class CMsgClientToGCCancelInviteToGuildResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    NoInviteFound = 6
    NoPermissions = 7


class CMsgClientToGCAddGuildRoleResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    NameAlreadyUsed = 6
    NoPermissions = 7
    InvalidFlags = 8
    InvalidName = 9
    AdminViolation = 10
    TooManyRoles = 11
    Blocked = 12


class CMsgClientToGCModifyGuildRoleResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    InvalidRole = 6
    NameAlreadyUsed = 7
    InvalidFlags = 8
    InvalidName = 9
    NoPermissions = 10
    AdminViolation = 11
    Blocked = 12


class CMsgClientToGCRemoveGuildRoleResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    InvalidRole = 6
    RoleNotEmpty = 7
    NoPermissions = 8
    AdminViolation = 9
    CantRemoveDefaultRole = 10


class CMsgClientToGCSetGuildRoleOrderResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    InvalidRole = 6
    InvalidOrder = 7
    NoPermissions = 8
    AdminViolation = 9


class CMsgClientToGCRequestGuildFeedResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    NoPermissions = 6


class CMsgClientToGCAddPlayerToGuildChatResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidGuild = 5
    NotMember = 6
    SteamChatNotEnabled = 7


class CMsgFindGuildByTagResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidTag = 5
    GuildNotFound = 6


class CMsgSearchForOpenGuildsResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4


class CMsgClientToGCReportGuildContentEContentFlags(betterproto.Enum):
    NONE = 0
    InappropriateName = 1
    InappropriateTag = 2
    InappropriateLogo = 4
    ValidFlags = 7


class CMsgClientToGCReportGuildContentResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    GuildNotFound = 5
    FlagsInvalid = 6


class CMsgClientToGCRequestAccountGuildPersonaInfoResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidAccount = 5


class CMsgClientToGCRequestAccountGuildPersonaInfoBatchResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidRequest = 5


@dataclass
class CMsgGuildInfo(betterproto.Message):
    guild_name: str = betterproto.string_field(1)
    guild_tag: str = betterproto.string_field(2)
    created_timestamp: int = betterproto.uint32_field(3)
    guild_language: int = betterproto.uint32_field(4)
    guild_flags: int = betterproto.uint32_field(5)
    guild_logo: int = betterproto.uint64_field(7)
    guild_region: int = betterproto.uint32_field(8)
    guild_chat_group_id: int = betterproto.uint64_field(9)
    guild_description: str = betterproto.string_field(10)
    default_chat_channel_id: int = betterproto.uint64_field(11)
    guild_primary_color: int = betterproto.uint32_field(12)
    guild_secondary_color: int = betterproto.uint32_field(13)
    guild_pattern: int = betterproto.uint32_field(14)
    guild_refresh_time_offset: int = betterproto.uint32_field(15)
    guild_required_rank_tier: int = betterproto.uint32_field(16)
    guild_motd_timestamp: int = betterproto.uint32_field(17)
    guild_motd: str = betterproto.string_field(18)


@dataclass
class CMsgGuildSummary(betterproto.Message):
    guild_info: "CMsgGuildInfo" = betterproto.message_field(1)
    member_count: int = betterproto.uint32_field(2)
    event_points: List["CMsgGuildSummaryEventPoints"] = betterproto.message_field(3)


@dataclass
class CMsgGuildSummaryEventPoints(betterproto.Message):
    event_id: int = betterproto.uint32_field(1)
    guild_points: int = betterproto.uint32_field(2)


@dataclass
class CMsgGuildRole(betterproto.Message):
    role_id: int = betterproto.uint32_field(1)
    role_name: str = betterproto.string_field(2)
    role_flags: int = betterproto.uint32_field(3)
    role_order: int = betterproto.uint32_field(4)


@dataclass
class CMsgGuildMember(betterproto.Message):
    member_account_id: int = betterproto.uint32_field(1)
    member_role_id: int = betterproto.uint32_field(2)
    member_joined_timestamp: int = betterproto.uint32_field(3)
    member_last_active_timestamp: int = betterproto.uint32_field(4)


@dataclass
class CMsgGuildInvite(betterproto.Message):
    requester_account_id: int = betterproto.uint32_field(1)
    target_account_id: int = betterproto.uint32_field(2)
    timestamp_sent: int = betterproto.uint32_field(3)


@dataclass
class CMsgGuildData(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    guild_info: "CMsgGuildInfo" = betterproto.message_field(2)
    guild_roles: List["CMsgGuildRole"] = betterproto.message_field(3)
    guild_members: List["CMsgGuildMember"] = betterproto.message_field(4)
    guild_invites: List["CMsgGuildInvite"] = betterproto.message_field(5)


@dataclass
class CMsgAccountGuildInvite(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    requester_account_id: int = betterproto.uint32_field(2)
    timestamp_sent: int = betterproto.uint32_field(3)


@dataclass
class CMsgAccountGuildMemberships(betterproto.Message):
    guild_ids: List[int] = betterproto.uint32_field(1)
    guild_invites: List["CMsgAccountGuildInvite"] = betterproto.message_field(2)


@dataclass
class CMsgGuildPersonaInfo(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    guild_tag: str = betterproto.string_field(2)
    guild_flags: int = betterproto.uint32_field(3)


@dataclass
class CMsgAccountGuildsPersonaInfo(betterproto.Message):
    guild_persona_infos: List["CMsgGuildPersonaInfo"] = betterproto.message_field(1)


@dataclass
class CMsgGuildFeedEvent(betterproto.Message):
    feed_event_id: int = betterproto.uint64_field(1)
    timestamp: int = betterproto.uint32_field(2)
    event_type: int = betterproto.uint32_field(3)
    param_uint_1: int = betterproto.uint32_field(4)
    param_uint_2: int = betterproto.uint32_field(5)
    param_uint_3: int = betterproto.uint32_field(6)


@dataclass
class CMsgClientToGCCreateGuild(betterproto.Message):
    guild_info: "CMsgGuildInfo" = betterproto.message_field(1)
    guild_chat_type: "EGuildChatType" = betterproto.enum_field(2)


@dataclass
class CMsgClientToGCCreateGuildResponse(betterproto.Message):
    result: "CMsgClientToGCCreateGuildResponseEResponse" = betterproto.enum_field(1)
    guild_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCSetGuildInfo(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    guild_info: "CMsgGuildInfo" = betterproto.message_field(2)
    guild_chat_type: "EGuildChatType" = betterproto.enum_field(3)


@dataclass
class CMsgClientToGCSetGuildInfoResponse(betterproto.Message):
    result: "CMsgClientToGCSetGuildInfoResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCRequestGuildData(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCRequestGuildDataResponse(betterproto.Message):
    result: "CMsgClientToGCRequestGuildDataResponseEResponse" = betterproto.enum_field(1)
    guild_data: "CMsgGuildData" = betterproto.message_field(2)


@dataclass
class CMsgGCToClientGuildDataUpdated(betterproto.Message):
    guild_data: "CMsgGuildData" = betterproto.message_field(1)
    update_flags: int = betterproto.uint32_field(2)


@dataclass
class CMsgGCToClientGuildMembersDataUpdated(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    members_data: List["CMsgGuildMember"] = betterproto.message_field(2)


@dataclass
class CMsgClientToGCRequestGuildMembership(betterproto.Message):
    pass


@dataclass
class CMsgClientToGCRequestGuildMembershipResponse(betterproto.Message):
    result: "CMsgClientToGCRequestGuildMembershipResponseEResponse" = betterproto.enum_field(1)
    guild_memberships: "CMsgAccountGuildMemberships" = betterproto.message_field(2)


@dataclass
class CMsgGCToClientGuildMembershipUpdated(betterproto.Message):
    guild_memberships: "CMsgAccountGuildMemberships" = betterproto.message_field(1)


@dataclass
class CMsgClientToGCRequestGuildSummary(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCRequestGuildSummaryResponse(betterproto.Message):
    result: "CMsgClientToGCRequestGuildSummaryResponseEResponse" = betterproto.enum_field(1)
    guild_summary: "CMsgGuildSummary" = betterproto.message_field(2)


@dataclass
class CMsgClientToGCJoinGuild(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCJoinGuildResponse(betterproto.Message):
    result: "CMsgClientToGCJoinGuildResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCLeaveGuild(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCLeaveGuildResponse(betterproto.Message):
    result: "CMsgClientToGCLeaveGuildResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCKickGuildMember(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    target_account_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCKickGuildMemberResponse(betterproto.Message):
    result: "CMsgClientToGCKickGuildMemberResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCSetGuildMemberRole(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    target_account_id: int = betterproto.uint32_field(2)
    target_role_id: int = betterproto.uint32_field(3)


@dataclass
class CMsgClientToGCSetGuildMemberRoleResponse(betterproto.Message):
    result: "CMsgClientToGCSetGuildMemberRoleResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCInviteToGuild(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    target_account_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCInviteToGuildResponse(betterproto.Message):
    result: "CMsgClientToGCInviteToGuildResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCDeclineInviteToGuild(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCDeclineInviteToGuildResponse(betterproto.Message):
    result: "CMsgClientToGCDeclineInviteToGuildResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCAcceptInviteToGuild(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCAcceptInviteToGuildResponse(betterproto.Message):
    result: "CMsgClientToGCAcceptInviteToGuildResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCCancelInviteToGuild(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    target_account_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCCancelInviteToGuildResponse(betterproto.Message):
    result: "CMsgClientToGCCancelInviteToGuildResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCAddGuildRole(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    role_name: str = betterproto.string_field(2)
    role_flags: int = betterproto.uint32_field(3)


@dataclass
class CMsgClientToGCAddGuildRoleResponse(betterproto.Message):
    result: "CMsgClientToGCAddGuildRoleResponseEResponse" = betterproto.enum_field(1)
    role_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCModifyGuildRole(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    role_id: int = betterproto.uint32_field(2)
    role_name: str = betterproto.string_field(3)
    role_flags: int = betterproto.uint32_field(4)


@dataclass
class CMsgClientToGCModifyGuildRoleResponse(betterproto.Message):
    result: "CMsgClientToGCModifyGuildRoleResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCRemoveGuildRole(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    role_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCRemoveGuildRoleResponse(betterproto.Message):
    result: "CMsgClientToGCRemoveGuildRoleResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCSetGuildRoleOrder(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    requested_role_ids: List[int] = betterproto.uint32_field(2)
    previous_role_ids: List[int] = betterproto.uint32_field(3)


@dataclass
class CMsgClientToGCSetGuildRoleOrderResponse(betterproto.Message):
    result: "CMsgClientToGCSetGuildRoleOrderResponseEResponse" = betterproto.enum_field(1)
    confirmed_role_ids: List[int] = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCGuildFeedRequest(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    last_seen_id: int = betterproto.uint64_field(2)


@dataclass
class CMsgClientToGCRequestGuildFeedResponse(betterproto.Message):
    result: "CMsgClientToGCRequestGuildFeedResponseEResponse" = betterproto.enum_field(1)
    guild_id: int = betterproto.uint32_field(2)
    feed_events: List["CMsgGuildFeedEvent"] = betterproto.message_field(3)


@dataclass
class CMsgGCToClientGuildFeedUpdated(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCAddPlayerToGuildChat(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCAddPlayerToGuildChatResponse(betterproto.Message):
    result: "CMsgClientToGCAddPlayerToGuildChatResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgFindGuildByTagResponse(betterproto.Message):
    result: "CMsgFindGuildByTagResponseEResponse" = betterproto.enum_field(1)
    guild_id: int = betterproto.uint32_field(2)
    guild_summary: "CMsgGuildSummary" = betterproto.message_field(3)


@dataclass
class CMsgSearchForOpenGuildsResponse(betterproto.Message):
    result: "CMsgSearchForOpenGuildsResponseEResponse" = betterproto.enum_field(1)
    search_results: List["CMsgSearchForOpenGuildsResponseSearchResult"] = betterproto.message_field(2)
    use_whitelist: bool = betterproto.bool_field(3)


@dataclass
class CMsgSearchForOpenGuildsResponseSearchResult(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    guild_summary: "CMsgGuildSummary" = betterproto.message_field(2)


@dataclass
class CMsgClientToGCReportGuildContent(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    guild_content_flags: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCReportGuildContentResponse(betterproto.Message):
    result: "CMsgClientToGCReportGuildContentResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCRequestAccountGuildPersonaInfo(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCRequestAccountGuildPersonaInfoResponse(betterproto.Message):
    result: "CMsgClientToGCRequestAccountGuildPersonaInfoResponseEResponse" = betterproto.enum_field(1)
    persona_info: "CMsgAccountGuildsPersonaInfo" = betterproto.message_field(2)


@dataclass
class CMsgClientToGCRequestAccountGuildPersonaInfoBatch(betterproto.Message):
    account_ids: List[int] = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCRequestAccountGuildPersonaInfoBatchResponse(betterproto.Message):
    result: "CMsgClientToGCRequestAccountGuildPersonaInfoBatchResponseEResponse" = betterproto.enum_field(1)
    persona_infos: List["CMsgAccountGuildsPersonaInfo"] = betterproto.message_field(2)
