# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: econ_gcmessages.proto
# plugin: python-betterproto

from dataclasses import dataclass
from typing import List

import betterproto

from .econ_shared_enums import EgcMsgResponse, EgcPartnerRequestResponse


class EgcMsgInitiateTradeResponse(betterproto.Enum):
    Accepted = 0
    Declined = 1
    VacBannedInitiator = 2
    VacBannedTarget = 3
    TargetAlreadyTrading = 4
    Disabled = 5
    NotLoggedIn = 6
    Cancel = 7
    TooSoon = 8
    TooSoonPenalty = 9
    TradeBannedInitiator = 10
    TradeBannedTarget = 11
    FreeAccountInitiatorDeprecated = 12
    SharedAccountInitiator = 13
    ServiceUnavailable = 14
    TargetBlocked = 15
    NeedVerifiedEmail = 16
    NeedSteamGuard = 17
    SteamGuardDuration = 18
    TheyCannotTrade = 19
    RecentPasswordReset = 20
    UsingNewDevice = 21
    SentInvalidCookie = 22
    TooRecentFriend = 23
    WalledFundsNotTrusted = 24

class CMsgClientToGcUnpackBundleResponseEUnpackBundle(betterproto.Enum):
    Succeeded = 0
    FailedItemIsNotBundle = 1
    FailedUnableToCreateContainedItem = 2
    FailedSOCacheError = 3
    FailedItemIsInvalid = 4
    FailedBadItemQuantity = 5
    FailedUnableToDeleteItem = 6


class CMsgClientToGcSetItemStyleResponseESetStyle(betterproto.Enum):
    Succeeded = 0
    Failed = 1
    FailedStyleIsLocked = 2


class CMsgClientToGcUnlockItemStyleResponseEUnlockStyle(betterproto.Enum):
    Succeeded = 0
    FailedPreReq = 1
    FailedCantAfford = 2
    FailedCantCommit = 3
    FailedCantLockCache = 4
    FailedCantAffordAttrib = 5
    FailedCantAffordGem = 6
    FailedNoCompendiumLevel = 7
    FailedAlreadyUnlocked = 8
    FailedOtherError = 9
    FailedItemIsInvalid = 10
    FailedToolIsInvalid = 11


class CMsgClientToGcRemoveItemAttributeResponseERemoveItemAttribute(betterproto.Enum):
    Succeeded = 0
    Failed = 1
    FailedItemIsInvalid = 2
    FailedAttributeCannotBeRemoved = 3
    FailedAttributeDoesntExist = 4


class CMsgClientToGcNameItemResponseENameItem(betterproto.Enum):
    Succeeded = 0
    Failed = 1
    FailedToolIsInvalid = 2
    FailedItemIsInvalid = 3
    FailedNameIsInvalid = 4


class CMsgClientToGcCreateStaticRecipeResponseEResponse(betterproto.Enum):
    Success = 0
    OfferingDisabled = 1
    InvalidItems = 2
    InternalError = 3
    MissingLeague = 4
    MissingEvent = 5


class CMsgClientToGcGetLimitedItemPurchaseQuantityResponseEResponse(betterproto.Enum):
    InternalError = 0
    Success = 1
    TooBusy = 2
    Disabled = 3
    Timeout = 4
    InvalidItemDef = 5
    ItemDefNotLimited = 6


@dataclass(eq=False, repr=False)
class CMsgApplyAutograph(betterproto.Message):
    autograph_item_id: int = betterproto.uint64_field(1)
    item_item_id: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class CMsgAdjustItemEquippedState(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)
    new_class: int = betterproto.uint32_field(2)
    new_slot: int = betterproto.uint32_field(3)
    style_index: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CMsgEconPlayerStrangeCountAdjustment(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    strange_count_adjustments: List[
        "CMsgEconPlayerStrangeCountAdjustmentCStrangeCountAdjustment"
    ] = betterproto.message_field(2)
    turbo_mode: bool = betterproto.bool_field(3)


@dataclass(eq=False, repr=False)
class CMsgEconPlayerStrangeCountAdjustmentCStrangeCountAdjustment(betterproto.Message):
    event_type: int = betterproto.uint32_field(1)
    item_id: int = betterproto.uint64_field(2)
    adjustment: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CMsgRequestItemPurgatoryFinalizePurchase(betterproto.Message):
    item_ids: List[int] = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class CMsgRequestItemPurgatoryFinalizePurchaseResponse(betterproto.Message):
    result: int = betterproto.uint32_field(1)
    item_ids: List[int] = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class CMsgRequestItemPurgatoryRefundPurchase(betterproto.Message):
    item_ids: List[int] = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class CMsgRequestItemPurgatoryRefundPurchaseResponse(betterproto.Message):
    result: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class CMsgCraftingResponse(betterproto.Message):
    item_ids: List[int] = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcRequestStoreSalesData(betterproto.Message):
    version: int = betterproto.uint32_field(1)
    currency: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcRequestStoreSalesDataResponse(betterproto.Message):
    sale_price: List["CMsgGcRequestStoreSalesDataResponsePrice"] = betterproto.message_field(1)
    version: int = betterproto.uint32_field(2)
    expiration_time: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CMsgGcRequestStoreSalesDataResponsePrice(betterproto.Message):
    item_def: int = betterproto.uint32_field(1)
    price: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcRequestStoreSalesDataUpToDateResponse(betterproto.Message):
    version: int = betterproto.uint32_field(1)
    expiration_time: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcToGcPingRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class CMsgGcToGcPingResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class CMsgGcToGcGetUserSessionServer(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcToGcGetUserSessionServerResponse(betterproto.Message):
    server_steam_id: int = betterproto.fixed64_field(1)
    is_online: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcToGcGetUserServerMembers(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    max_spectators: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcToGcGetUserServerMembersResponse(betterproto.Message):
    member_account_id: List[int] = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class CMsgLookupMultipleAccountNames(betterproto.Message):
    accountids: List[int] = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class CMsgLookupMultipleAccountNamesResponse(betterproto.Message):
    accounts: List["CMsgLookupMultipleAccountNamesResponseAccount"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CMsgLookupMultipleAccountNamesResponseAccount(betterproto.Message):
    accountid: int = betterproto.uint32_field(1)
    persona: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class CMsgRequestCrateItems(betterproto.Message):
    crate_item_def: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class CMsgRequestCrateItemsResponse(betterproto.Message):
    response: int = betterproto.uint32_field(1)
    item_defs: List[int] = betterproto.uint32_field(2)
    peek_item_defs: List[int] = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CMsgRequestCrateEscalationLevel(betterproto.Message):
    crate_item_def: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class CMsgRequestCrateEscalationLevelResponse(betterproto.Message):
    response: int = betterproto.uint32_field(1)
    escalation_level0: int = betterproto.uint32_field(2)
    escalation_level1: int = betterproto.uint32_field(3)
    escalation_level2: int = betterproto.uint32_field(4)
    escalation_level3: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class CMsgGcToGcCanUseDropRateBonus(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    drop_rate_bonus: float = betterproto.float_field(2)
    booster_type: int = betterproto.uint32_field(3)
    exclusive_item_def: int = betterproto.uint32_field(4)
    allow_equal_rate: bool = betterproto.bool_field(5)


@dataclass(eq=False, repr=False)
class CMsgSqlAddDropRateBonus(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    item_id: int = betterproto.uint64_field(2)
    item_def: int = betterproto.uint32_field(3)
    drop_rate_bonus: float = betterproto.float_field(4)
    booster_type: int = betterproto.uint32_field(5)
    seconds_duration: int = betterproto.uint32_field(6)
    end_time_stamp: int = betterproto.uint32_field(7)


@dataclass(eq=False, repr=False)
class CMsgSqlUpgradeBattleBooster(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    item_def: int = betterproto.uint32_field(2)
    bonus_to_add: float = betterproto.float_field(3)
    booster_type: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CMsgGcToGcRefreshSoCache(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    reload: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcToGcCheckAccountTradeStatus(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    initiator: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcToGcCheckAccountTradeStatusResponse(betterproto.Message):
    can_trade: bool = betterproto.bool_field(1)
    error_code: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcToGcAddSubscriptionTime(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    matching_subscription_def_indexes: List[int] = betterproto.uint32_field(2)
    additional_seconds: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CMsgGcToGcGrantAccountRolledItems(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    items: List["CMsgGcToGcGrantAccountRolledItemsItem"] = betterproto.message_field(2)
    audit_action: int = betterproto.uint32_field(3)
    audit_data: int = betterproto.uint64_field(4)


@dataclass(eq=False, repr=False)
class CMsgGcToGcGrantAccountRolledItemsItem(betterproto.Message):
    item_def: int = betterproto.uint32_field(1)
    loot_lists: List[str] = betterproto.string_field(2)
    ignore_limit: bool = betterproto.bool_field(3)
    origin: int = betterproto.uint32_field(4)
    dynamic_attributes: List["CMsgGcToGcGrantAccountRolledItemsItemDynamicAttribute"] = betterproto.message_field(5)
    additional_audit_entries: List[
        "CMsgGcToGcGrantAccountRolledItemsItemAdditionalAuditEntry"
    ] = betterproto.message_field(6)
    inventory_token: int = betterproto.uint32_field(7)


@dataclass(eq=False, repr=False)
class CMsgGcToGcGrantAccountRolledItemsItemDynamicAttribute(betterproto.Message):
    name: str = betterproto.string_field(1)
    value_uint32: int = betterproto.uint32_field(2)
    value_float: float = betterproto.float_field(3)
    value_string: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class CMsgGcToGcGrantAccountRolledItemsItemAdditionalAuditEntry(betterproto.Message):
    owner_account_id: int = betterproto.uint32_field(1)
    audit_action: int = betterproto.uint32_field(2)
    audit_data: int = betterproto.uint64_field(3)


@dataclass(eq=False, repr=False)
class CMsgGcToGcGrantSelfMadeItemToAccount(betterproto.Message):
    item_def_index: int = betterproto.uint32_field(1)
    accountid: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgUseItem(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)
    target_steam_id: int = betterproto.fixed64_field(2)
    gift_potential_targets: List[int] = betterproto.uint32_field(3)
    duel_class_lock: int = betterproto.uint32_field(4)
    initiator_steam_id: int = betterproto.uint64_field(5)
    itempack_ack_immediately: bool = betterproto.bool_field(6)


@dataclass(eq=False, repr=False)
class CMsgServerUseItem(betterproto.Message):
    initiator_account_id: int = betterproto.uint32_field(1)
    use_item_msg: "CMsgUseItem" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CMsgUseMultipleItems(betterproto.Message):
    item_ids: List[int] = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcPartnerBalanceRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class CMsgGcPartnerBalanceResponse(betterproto.Message):
    result: "EgcPartnerRequestResponse" = betterproto.enum_field(1)
    balance: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CgcStoreRechargeRedirectLineItem(betterproto.Message):
    item_def_id: int = betterproto.uint32_field(1)
    quantity: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcPartnerRechargeRedirectUrlRequest(betterproto.Message):
    line_items: List["CgcStoreRechargeRedirectLineItem"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcPartnerRechargeRedirectUrlResponse(betterproto.Message):
    result: "EgcPartnerRequestResponse" = betterproto.enum_field(1)
    url: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcEconSqlWorkItemEmbeddedRollbackData(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    deleted_item_id: int = betterproto.uint64_field(2)
    old_audit_action: int = betterproto.uint32_field(3)
    new_audit_action: int = betterproto.uint32_field(4)
    expected_audit_action: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class CMsgCraftStatue(betterproto.Message):
    heroid: int = betterproto.uint32_field(1)
    sequencename: str = betterproto.string_field(2)
    cycle: float = betterproto.float_field(3)
    description: str = betterproto.string_field(4)
    pedestal_itemdef: int = betterproto.uint32_field(5)
    toolid: int = betterproto.uint64_field(6)


@dataclass(eq=False, repr=False)
class CMsgRedeemCode(betterproto.Message):
    code: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class CMsgRedeemCodeResponse(betterproto.Message):
    response: int = betterproto.uint32_field(1)
    item_id: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class CMsgDevNewItemRequest(betterproto.Message):
    item_def_name: str = betterproto.string_field(3)
    loot_list_name: str = betterproto.string_field(4)
    attr_def_name: List[str] = betterproto.string_field(5)
    attr_value: List[str] = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class CMsgDevNewItemRequestResponse(betterproto.Message):
    success: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class CMsgDevUnlockAllItemStyles(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class CMsgDevUnlockAllItemStylesResponse(betterproto.Message):
    success: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcGetAccountSubscriptionItem(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcGetAccountSubscriptionItemResponse(betterproto.Message):
    def_index: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcAddGiftItem(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    item_id: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcWrapAndDeliverGift(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)
    give_to_account_id: int = betterproto.uint32_field(2)
    gift_message: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class CMsgClientToGcWrapAndDeliverGiftResponse(betterproto.Message):
    response: "EgcMsgResponse" = betterproto.enum_field(1)
    gifting_charge_uses: int = betterproto.uint32_field(2)
    gifting_charge_max: int = betterproto.int32_field(3)
    gifting_uses: int = betterproto.uint32_field(4)
    gifting_max: int = betterproto.int32_field(5)
    gifting_window_hours: int = betterproto.uint32_field(6)
    trade_restriction: "EgcMsgInitiateTradeResponse" = betterproto.enum_field(7)


@dataclass(eq=False, repr=False)
class CMsgClientToGcUnwrapGift(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class CMsgClientToGcGetGiftPermissions(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class CMsgClientToGcGetGiftPermissionsResponse(betterproto.Message):
    is_unlimited: bool = betterproto.bool_field(1)
    has_two_factor: bool = betterproto.bool_field(3)
    sender_permission: "EgcMsgInitiateTradeResponse" = betterproto.enum_field(6)
    friendship_age_requirement: int = betterproto.uint32_field(7)
    friendship_age_requirement_two_factor: int = betterproto.uint32_field(8)
    friend_permissions: List["CMsgClientToGcGetGiftPermissionsResponseFriendPermission"] = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class CMsgClientToGcGetGiftPermissionsResponseFriendPermission(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    permission: "EgcMsgInitiateTradeResponse" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcUnpackBundle(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class CMsgClientToGcUnpackBundleResponse(betterproto.Message):
    unpacked_item_ids: List[int] = betterproto.uint64_field(1)
    response: "CMsgClientToGcUnpackBundleResponseEUnpackBundle" = betterproto.enum_field(2)
    unpacked_item_def_indexes: List[int] = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CMsgGcToClientStoreTransactionCompleted(betterproto.Message):
    txn_id: int = betterproto.uint64_field(1)
    item_ids: List[int] = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcEquipItems(betterproto.Message):
    equips: List["CMsgAdjustItemEquippedState"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CMsgClientToGcEquipItemsResponse(betterproto.Message):
    so_cache_version_id: int = betterproto.fixed64_field(1)


@dataclass(eq=False, repr=False)
class CMsgClientToGcSetItemStyle(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)
    style_index: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcSetItemStyleResponse(betterproto.Message):
    response: "CMsgClientToGcSetItemStyleResponseESetStyle" = betterproto.enum_field(1)


@dataclass(eq=False, repr=False)
class CMsgClientToGcUnlockItemStyle(betterproto.Message):
    item_to_unlock: int = betterproto.uint64_field(1)
    style_index: int = betterproto.uint32_field(2)
    consumable_item_ids: List[int] = betterproto.uint64_field(3)


@dataclass(eq=False, repr=False)
class CMsgClientToGcUnlockItemStyleResponse(betterproto.Message):
    response: "CMsgClientToGcUnlockItemStyleResponseEUnlockStyle" = betterproto.enum_field(1)
    item_id: int = betterproto.uint64_field(2)
    style_index: int = betterproto.uint32_field(3)
    style_prereq: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CMsgClientToGcSetItemInventoryCategory(betterproto.Message):
    item_ids: List[int] = betterproto.uint64_field(1)
    set_to_value: int = betterproto.uint32_field(2)
    remove_categories: int = betterproto.uint32_field(3)
    add_categories: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CMsgClientToGcUnlockCrate(betterproto.Message):
    crate_item_id: int = betterproto.uint64_field(1)
    key_item_id: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcUnlockCrateResponse(betterproto.Message):
    result: "EgcMsgResponse" = betterproto.enum_field(1)
    granted_items: List["CMsgClientToGcUnlockCrateResponseItem"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcUnlockCrateResponseItem(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)
    def_index: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcRemoveItemAttribute(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class CMsgClientToGcRemoveItemAttributeResponse(betterproto.Message):
    response: "CMsgClientToGcRemoveItemAttributeResponseERemoveItemAttribute" = betterproto.enum_field(1)
    item_id: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcNameItem(betterproto.Message):
    subject_item_id: int = betterproto.uint64_field(1)
    tool_item_id: int = betterproto.uint64_field(2)
    name: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class CMsgClientToGcNameItemResponse(betterproto.Message):
    response: "CMsgClientToGcNameItemResponseENameItem" = betterproto.enum_field(1)
    item_id: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcSetItemPosition(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)
    new_position: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CAttributeItemDynamicRecipeComponent(betterproto.Message):
    item_def: int = betterproto.uint32_field(1)
    item_quality: int = betterproto.uint32_field(2)
    item_flags: int = betterproto.uint32_field(3)
    attributes_string: str = betterproto.string_field(4)
    item_count: int = betterproto.uint32_field(5)
    items_fulfilled: int = betterproto.uint32_field(6)
    item_rarity: int = betterproto.uint32_field(7)
    lootlist: str = betterproto.string_field(8)
    fulfilled_item_id: int = betterproto.uint64_field(9)


@dataclass(eq=False, repr=False)
class CProtoItemSocket(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)
    attr_def_index: int = betterproto.uint32_field(2)
    required_type: int = betterproto.uint32_field(3)
    required_hero: str = betterproto.string_field(4)
    gem_def_index: int = betterproto.uint32_field(5)
    not_tradable: bool = betterproto.bool_field(6)
    required_item_slot: str = betterproto.string_field(7)


@dataclass(eq=False, repr=False)
class CProtoItemSocketEmpty(betterproto.Message):
    socket: "CProtoItemSocket" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CProtoItemSocketEffect(betterproto.Message):
    socket: "CProtoItemSocket" = betterproto.message_field(1)
    effect: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CProtoItemSocketColor(betterproto.Message):
    socket: "CProtoItemSocket" = betterproto.message_field(1)
    red: int = betterproto.uint32_field(2)
    green: int = betterproto.uint32_field(3)
    blue: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CProtoItemSocketStrange(betterproto.Message):
    socket: "CProtoItemSocket" = betterproto.message_field(1)
    strange_type: int = betterproto.uint32_field(2)
    strange_value: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CProtoItemSocketStrangeDeserializeFromStringOnly(betterproto.Message):
    socket: "CProtoItemSocket" = betterproto.message_field(1)
    strange_type: int = betterproto.uint32_field(2)
    strange_value: int = betterproto.uint32_field(3)
    ability_effect: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CProtoItemSocketSpectator(betterproto.Message):
    socket: "CProtoItemSocket" = betterproto.message_field(1)
    games_viewed: int = betterproto.uint32_field(2)
    corporation_id: int = betterproto.uint32_field(3)
    league_id: int = betterproto.uint32_field(4)
    team_id: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class CProtoItemSocketAssetModifier(betterproto.Message):
    socket: "CProtoItemSocket" = betterproto.message_field(1)
    asset_modifier: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CProtoItemSocketAssetModifierDeserializeFromStringOnly(betterproto.Message):
    socket: "CProtoItemSocket" = betterproto.message_field(1)
    asset_modifier: int = betterproto.uint32_field(2)
    anim_modifier: int = betterproto.uint32_field(3)
    ability_effect: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CProtoItemSocketAutograph(betterproto.Message):
    socket: "CProtoItemSocket" = betterproto.message_field(1)
    autograph: str = betterproto.string_field(2)
    autograph_id: int = betterproto.uint32_field(3)
    autograph_score: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CProtoItemSocketStaticVisuals(betterproto.Message):
    socket: "CProtoItemSocket" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CAttributeString(betterproto.Message):
    value: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class CWorkshopGetItemDailyRevenueRequest(betterproto.Message):
    appid: int = betterproto.uint32_field(1)
    item_id: int = betterproto.uint32_field(2)
    date_start: int = betterproto.uint32_field(3)
    date_end: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class CWorkshopGetItemDailyRevenueResponse(betterproto.Message):
    country_revenue: List["CWorkshopGetItemDailyRevenueResponseCountryDailyRevenue"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CWorkshopGetItemDailyRevenueResponseCountryDailyRevenue(betterproto.Message):
    country_code: str = betterproto.string_field(1)
    date: int = betterproto.uint32_field(2)
    revenue_usd: int = betterproto.int64_field(3)
    units: int = betterproto.int32_field(4)


@dataclass(eq=False, repr=False)
class CWorkshopGetPackageDailyRevenueRequest(betterproto.Message):
    packageid: int = betterproto.uint32_field(1)
    date_start: int = betterproto.uint32_field(2)
    date_end: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CWorkshopGetPackageDailyRevenueResponse(betterproto.Message):
    country_revenue: List["CWorkshopGetPackageDailyRevenueResponseCountryDailyRevenue"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CWorkshopGetPackageDailyRevenueResponseCountryDailyRevenue(betterproto.Message):
    country_code: str = betterproto.string_field(1)
    date: int = betterproto.uint32_field(2)
    revenue_usd: int = betterproto.int64_field(3)
    units: int = betterproto.int32_field(4)


@dataclass(eq=False, repr=False)
class CMsgSqlgcToGcGrantBackpackSlots(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    add_slots: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcLookupAccountName(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class CMsgClientToGcLookupAccountNameResponse(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    account_name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcCreateStaticRecipe(betterproto.Message):
    items: List["CMsgClientToGcCreateStaticRecipeItem"] = betterproto.message_field(1)
    recipe_def_index: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcCreateStaticRecipeItem(betterproto.Message):
    item_id: int = betterproto.uint64_field(1)
    slot_id: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcCreateStaticRecipeResponse(betterproto.Message):
    response: "CMsgClientToGcCreateStaticRecipeResponseEResponse" = betterproto.enum_field(1)
    output_items: List["CMsgClientToGcCreateStaticRecipeResponseOutputItem"] = betterproto.message_field(2)
    input_errors: List["CMsgClientToGcCreateStaticRecipeResponseInputError"] = betterproto.message_field(3)
    additional_outputs: List["CMsgClientToGcCreateStaticRecipeResponseAdditionalOutput"] = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class CMsgClientToGcCreateStaticRecipeResponseOutputItem(betterproto.Message):
    def_index: int = betterproto.uint32_field(1)
    item_id: int = betterproto.uint64_field(2)
    slot_id: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CMsgClientToGcCreateStaticRecipeResponseInputError(betterproto.Message):
    slot_id: int = betterproto.uint32_field(1)
    error: "CMsgClientToGcCreateStaticRecipeResponseEResponse" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class CMsgClientToGcCreateStaticRecipeResponseAdditionalOutput(betterproto.Message):
    slot_id: int = betterproto.uint32_field(1)
    value: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class CMsgProcessTransactionOrder(betterproto.Message):
    txn_id: int = betterproto.uint64_field(1)
    steam_txn_id: int = betterproto.uint64_field(2)
    partner_txn_id: int = betterproto.uint64_field(3)
    steam_id: int = betterproto.fixed64_field(4)
    time_stamp: int = betterproto.uint32_field(5)
    watermark: int = betterproto.uint64_field(6)
    purchase_report_status: int = betterproto.int32_field(7)
    currency: int = betterproto.uint32_field(8)
    items: List["CMsgProcessTransactionOrderItem"] = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class CMsgProcessTransactionOrderItem(betterproto.Message):
    item_def_index: int = betterproto.uint32_field(1)
    item_price: int = betterproto.uint32_field(2)
    quantity: int = betterproto.uint32_field(3)
    category_desc: str = betterproto.string_field(4)
    store_purchase_type: int = betterproto.uint32_field(5)
    source_reference_id: int = betterproto.uint64_field(6)
    parent_stack_index: int = betterproto.int32_field(7)
    default_price: bool = betterproto.bool_field(8)
    is_user_facing: bool = betterproto.bool_field(9)


@dataclass(eq=False, repr=False)
class CMsgGcToGcStoreProcessCdKeyTransaction(betterproto.Message):
    order: "CMsgProcessTransactionOrder" = betterproto.message_field(1)
    reason_code: int = betterproto.uint32_field(2)
    partner: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class CMsgGcToGcStoreProcessCdKeyTransactionResponse(betterproto.Message):
    success: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcToGcStoreProcessSettlement(betterproto.Message):
    order: "CMsgProcessTransactionOrder" = betterproto.message_field(1)
    partner: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcToGcStoreProcessSettlementResponse(betterproto.Message):
    success: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcToGcBroadcastConsoleCommand(betterproto.Message):
    con_command: str = betterproto.string_field(1)
    report_output: bool = betterproto.bool_field(2)
    sending_gc: int = betterproto.uint32_field(3)
    output_initiator: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class CMsgGcToGcConsoleOutput(betterproto.Message):
    initiator: str = betterproto.string_field(1)
    sending_gc: int = betterproto.uint32_field(2)
    msgs: List["CMsgGcToGcConsoleOutputOutputLine"] = betterproto.message_field(3)
    is_last_for_source_job: bool = betterproto.bool_field(4)


@dataclass(eq=False, repr=False)
class CMsgGcToGcConsoleOutputOutputLine(betterproto.Message):
    text: str = betterproto.string_field(1)
    spew_level: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class CMsgItemAges(betterproto.Message):
    max_item_id_timestamps: List["CMsgItemAgesMaxItemIdTimestamp"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CMsgItemAgesMaxItemIdTimestamp(betterproto.Message):
    timestamp: int = betterproto.uint32_field(1)
    max_item_id: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcToGcInternalTestMsg(betterproto.Message):
    sending_gc: int = betterproto.uint32_field(1)
    sender_id: int = betterproto.fixed64_field(2)
    context: int = betterproto.uint32_field(3)
    message_id: int = betterproto.uint32_field(4)
    message_body: bytes = betterproto.bytes_field(5)
    job_id_source: int = betterproto.fixed64_field(6)
    job_id_target: int = betterproto.fixed64_field(7)


@dataclass(eq=False, repr=False)
class CMsgGcToGcClientServerVersionsUpdated(betterproto.Message):
    client_min_allowed_version: int = betterproto.uint32_field(1)
    client_active_version: int = betterproto.uint32_field(2)
    server_active_version: int = betterproto.uint32_field(3)
    server_deployed_version: int = betterproto.uint32_field(4)
    what_changed: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class CMsgGcToGcBroadcastMessageFromSub(betterproto.Message):
    msg_id: int = betterproto.uint32_field(1)
    serialized_msg: bytes = betterproto.bytes_field(2)
    account_id_list: List[int] = betterproto.uint32_field(3)
    steam_id_list: List[int] = betterproto.fixed64_field(4)


@dataclass(eq=False, repr=False)
class CMsgGcToClientCurrencyPricePoints(betterproto.Message):
    price_key: List[int] = betterproto.uint64_field(1)
    currencies: List["CMsgGcToClientCurrencyPricePointsCurrency"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcToClientCurrencyPricePointsCurrency(betterproto.Message):
    currency_id: int = betterproto.uint32_field(1)
    currency_price: List[int] = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class CMsgBannedWordList(betterproto.Message):
    version: int = betterproto.uint32_field(1)
    banned_words: List[str] = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class CEconFlushInventoryCacheRequest(betterproto.Message):
    steamid: int = betterproto.uint64_field(1)
    appid: int = betterproto.uint32_field(2)
    contextid: int = betterproto.uint64_field(3)


@dataclass(eq=False, repr=False)
class CEconFlushInventoryCacheResponse(betterproto.Message):
    success: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcToGcFlushSteamInventoryCache(betterproto.Message):
    keys: List["CMsgGcToGcFlushSteamInventoryCacheKey"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcToGcFlushSteamInventoryCacheKey(betterproto.Message):
    steamid: int = betterproto.uint64_field(1)
    contextid: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcToGcUpdateSubscriptionItems(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    always_notify: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class CMsgGcToGcSelfPing(betterproto.Message):
    sample_id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class CMsgGcToGcGetInfuxIntervalStats(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class CMsgGcToGcGetInfuxIntervalStatsResponse(betterproto.Message):
    stat_ids: List[int] = betterproto.fixed32_field(1)
    stat_total: List[int] = betterproto.uint64_field(2)
    stat_samples: List[int] = betterproto.uint32_field(3)
    stat_max: List[int] = betterproto.uint32_field(4)
    sample_duration_ms: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class CMsgGcToGcPurchaseSucceeded(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class CExtraMsgBlock(betterproto.Message):
    msg_type: int = betterproto.uint32_field(1)
    contents: bytes = betterproto.bytes_field(2)
    msg_key: int = betterproto.uint64_field(3)
    is_compressed: bool = betterproto.bool_field(4)


@dataclass(eq=False, repr=False)
class CMsgClientToGcGetLimitedItemPurchaseQuantity(betterproto.Message):
    item_def: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class CMsgClientToGcGetLimitedItemPurchaseQuantityResponse(betterproto.Message):
    result: "CMsgClientToGcGetLimitedItemPurchaseQuantityResponseEResponse" = betterproto.enum_field(1)
    quantity_purchased: int = betterproto.uint32_field(2)
